//Code generated by make_resources.go; DO NOT EDIT
package resources

import (
    "golang.org/x/text/language"

    "{{.CLDRPackage}}"

    "{{.CLDRPackage}}/resources/internal/locales"
)

type cldrData map[language.Tag]func() *cldr.Locale

var localeData = cldrData{
    {{- range $locale, $_ := .Numbers}}
        tag_{{$locale}}: locales.Get_{{$locale}},
    {{- end}}
}

{{range $tag, $_ := .Tags}}
var tag_{{$tag}} = language.Make("{{$tag}}")
{{- end}}