//Code generated by make_resources.go; DO NOT EDIT
package locales

import (
    "golang.org/x/text/language"

    "{{.CLDRPackage}}"
)

type cldrData map[language.Tag]func() *cldr.Locale

var LocaleData = cldrData{
    {{- range $locale, $_ := .Numbers}}
        tag_{{$locale}}: getLocale_{{$locale}},
    {{- end}}
}

{{range $tag, $_ := .Tags}}
var tag_{{$tag}} = language.Make("{{$tag}}")
{{- end}}