// Code generated by make_resources.go; DO NOT EDIT.
package resources

import (
    "golang.org/x/text/feature/plural"
    "golang.org/x/text/language"

    "{{.CLDRPackage}}"
)

type pluralForms []plural.Form
type pluralFunc func(ops *cldr.PluralOperands) plural.Form

{{range $i, $pg := .PluralGroups}}
func cardinal_{{$i}}() cldr.PluralData {
    // for locales: {{printf "%v" $pg.SplitLocales}}
    forms := pluralForms{
        {{- range $pg.PluralRules}}
            plural.{{.CountTitle}},
        {{- end}}
    }
    plFunc := func (ops *cldr.PluralOperands) plural.Form {
        {{- range $pg.PluralRules}}{{if .GoCondition}}
        // {{.Condition}}
        if {{.GoCondition}} {
            return plural.{{.CountTitle}}
        }{{end}}
        {{- end}}
        return plural.Other
    }

    return cldr.PluralData{Forms: forms, Func: plFunc}
}
{{end}}

var cardinalPlural = map[language.Tag]func() cldr.PluralData{
{{- range $locale, $funcName := .LocaleMap}}
    tag_{{$locale}}: {{$funcName}},
{{- end}}
}
