//Code generated by make_resources.go; DO NOT EDIT
package resources

import (
    "golang.org/x/text/language"

    "{{.CLDRPackage}}"
)

var cardinalPluralLocales = map[language.Tag]func() cldr.PluralData{
{{- range $loc, $plFunc := .PluralLocaleTags}}
    tag_{{$loc}}: {{$plFunc}},
{{- end}}
}