// Code generated by make_resources.go; DO NOT EDIT.

package locales

import "testing"

{{range .PluralRules}}
    func Test{{$.PluralType}}{{.Name}}(t *testing.T) {
    var tests []pluralFormTest
    {{range .PluralRules}}
        {{if .IntegerExamples}}tests = appendIntegerTests(tests, {{.CountTitle}}, {{printf "%#v" .IntegerExamples}}){{end}}
        {{if .DecimalExamples}}tests = appendDecimalTests(tests, {{.CountTitle}}, {{printf "%#v" .DecimalExamples}}){{end}}
    {{end}}
    locales := {{printf "%#v" .SplitLocales}}
    for _, locale := range locales {
    runTests(t, locale, tests)
    }
    }
{{end}}