//Code generated by make_resources.go; DO NOT EDIT
package resources

import (
	"golang.org/x/text/language"

	"github.com/razor-1/cldr"

	"github.com/razor-1/cldr/resources/internal/locales"
)

type cldrData map[language.Tag]func() *cldr.Locale

var localeData = cldrData{
	tag_af:             locales.Get_af,
	tag_af_NA:          locales.Get_af_NA,
	tag_af_ZA:          locales.Get_af_ZA,
	tag_agq:            locales.Get_agq,
	tag_agq_CM:         locales.Get_agq_CM,
	tag_ak:             locales.Get_ak,
	tag_ak_GH:          locales.Get_ak_GH,
	tag_am:             locales.Get_am,
	tag_am_ET:          locales.Get_am_ET,
	tag_ar:             locales.Get_ar,
	tag_ar_001:         locales.Get_ar_001,
	tag_ar_AE:          locales.Get_ar_AE,
	tag_ar_BH:          locales.Get_ar_BH,
	tag_ar_DJ:          locales.Get_ar_DJ,
	tag_ar_DZ:          locales.Get_ar_DZ,
	tag_ar_EG:          locales.Get_ar_EG,
	tag_ar_EH:          locales.Get_ar_EH,
	tag_ar_ER:          locales.Get_ar_ER,
	tag_ar_IL:          locales.Get_ar_IL,
	tag_ar_IQ:          locales.Get_ar_IQ,
	tag_ar_JO:          locales.Get_ar_JO,
	tag_ar_KM:          locales.Get_ar_KM,
	tag_ar_KW:          locales.Get_ar_KW,
	tag_ar_LB:          locales.Get_ar_LB,
	tag_ar_LY:          locales.Get_ar_LY,
	tag_ar_MA:          locales.Get_ar_MA,
	tag_ar_MR:          locales.Get_ar_MR,
	tag_ar_OM:          locales.Get_ar_OM,
	tag_ar_PS:          locales.Get_ar_PS,
	tag_ar_QA:          locales.Get_ar_QA,
	tag_ar_SA:          locales.Get_ar_SA,
	tag_ar_SD:          locales.Get_ar_SD,
	tag_ar_SO:          locales.Get_ar_SO,
	tag_ar_SS:          locales.Get_ar_SS,
	tag_ar_SY:          locales.Get_ar_SY,
	tag_ar_TD:          locales.Get_ar_TD,
	tag_ar_TN:          locales.Get_ar_TN,
	tag_ar_YE:          locales.Get_ar_YE,
	tag_as:             locales.Get_as,
	tag_as_IN:          locales.Get_as_IN,
	tag_asa:            locales.Get_asa,
	tag_asa_TZ:         locales.Get_asa_TZ,
	tag_ast:            locales.Get_ast,
	tag_ast_ES:         locales.Get_ast_ES,
	tag_az:             locales.Get_az,
	tag_az_Cyrl:        locales.Get_az_Cyrl,
	tag_az_Cyrl_AZ:     locales.Get_az_Cyrl_AZ,
	tag_az_Latn:        locales.Get_az_Latn,
	tag_az_Latn_AZ:     locales.Get_az_Latn_AZ,
	tag_bas:            locales.Get_bas,
	tag_bas_CM:         locales.Get_bas_CM,
	tag_be:             locales.Get_be,
	tag_be_BY:          locales.Get_be_BY,
	tag_bem:            locales.Get_bem,
	tag_bem_ZM:         locales.Get_bem_ZM,
	tag_bez:            locales.Get_bez,
	tag_bez_TZ:         locales.Get_bez_TZ,
	tag_bg:             locales.Get_bg,
	tag_bg_BG:          locales.Get_bg_BG,
	tag_bm:             locales.Get_bm,
	tag_bm_ML:          locales.Get_bm_ML,
	tag_bn:             locales.Get_bn,
	tag_bn_BD:          locales.Get_bn_BD,
	tag_bn_IN:          locales.Get_bn_IN,
	tag_bo:             locales.Get_bo,
	tag_bo_CN:          locales.Get_bo_CN,
	tag_bo_IN:          locales.Get_bo_IN,
	tag_br:             locales.Get_br,
	tag_br_FR:          locales.Get_br_FR,
	tag_brx:            locales.Get_brx,
	tag_brx_IN:         locales.Get_brx_IN,
	tag_bs:             locales.Get_bs,
	tag_bs_Cyrl:        locales.Get_bs_Cyrl,
	tag_bs_Cyrl_BA:     locales.Get_bs_Cyrl_BA,
	tag_bs_Latn:        locales.Get_bs_Latn,
	tag_bs_Latn_BA:     locales.Get_bs_Latn_BA,
	tag_ca:             locales.Get_ca,
	tag_ca_AD:          locales.Get_ca_AD,
	tag_ca_ES:          locales.Get_ca_ES,
	tag_ca_ES_VALENCIA: locales.Get_ca_ES_VALENCIA,
	tag_ca_FR:          locales.Get_ca_FR,
	tag_ca_IT:          locales.Get_ca_IT,
	tag_ccp:            locales.Get_ccp,
	tag_ccp_BD:         locales.Get_ccp_BD,
	tag_ccp_IN:         locales.Get_ccp_IN,
	tag_ce:             locales.Get_ce,
	tag_ce_RU:          locales.Get_ce_RU,
	tag_ceb:            locales.Get_ceb,
	tag_ceb_PH:         locales.Get_ceb_PH,
	tag_cgg:            locales.Get_cgg,
	tag_cgg_UG:         locales.Get_cgg_UG,
	tag_chr:            locales.Get_chr,
	tag_chr_US:         locales.Get_chr_US,
	tag_ckb:            locales.Get_ckb,
	tag_ckb_IQ:         locales.Get_ckb_IQ,
	tag_ckb_IR:         locales.Get_ckb_IR,
	tag_cs:             locales.Get_cs,
	tag_cs_CZ:          locales.Get_cs_CZ,
	tag_cu:             locales.Get_cu,
	tag_cu_RU:          locales.Get_cu_RU,
	tag_cy:             locales.Get_cy,
	tag_cy_GB:          locales.Get_cy_GB,
	tag_da:             locales.Get_da,
	tag_da_DK:          locales.Get_da_DK,
	tag_da_GL:          locales.Get_da_GL,
	tag_dav:            locales.Get_dav,
	tag_dav_KE:         locales.Get_dav_KE,
	tag_de:             locales.Get_de,
	tag_de_AT:          locales.Get_de_AT,
	tag_de_BE:          locales.Get_de_BE,
	tag_de_CH:          locales.Get_de_CH,
	tag_de_DE:          locales.Get_de_DE,
	tag_de_IT:          locales.Get_de_IT,
	tag_de_LI:          locales.Get_de_LI,
	tag_de_LU:          locales.Get_de_LU,
	tag_dje:            locales.Get_dje,
	tag_dje_NE:         locales.Get_dje_NE,
	tag_dsb:            locales.Get_dsb,
	tag_dsb_DE:         locales.Get_dsb_DE,
	tag_dua:            locales.Get_dua,
	tag_dua_CM:         locales.Get_dua_CM,
	tag_dyo:            locales.Get_dyo,
	tag_dyo_SN:         locales.Get_dyo_SN,
	tag_dz:             locales.Get_dz,
	tag_dz_BT:          locales.Get_dz_BT,
	tag_ebu:            locales.Get_ebu,
	tag_ebu_KE:         locales.Get_ebu_KE,
	tag_ee:             locales.Get_ee,
	tag_ee_GH:          locales.Get_ee_GH,
	tag_ee_TG:          locales.Get_ee_TG,
	tag_el:             locales.Get_el,
	tag_el_CY:          locales.Get_el_CY,
	tag_el_GR:          locales.Get_el_GR,
	tag_en:             locales.Get_en,
	tag_en_001:         locales.Get_en_001,
	tag_en_150:         locales.Get_en_150,
	tag_en_AE:          locales.Get_en_AE,
	tag_en_AG:          locales.Get_en_AG,
	tag_en_AI:          locales.Get_en_AI,
	tag_en_AS:          locales.Get_en_AS,
	tag_en_AT:          locales.Get_en_AT,
	tag_en_AU:          locales.Get_en_AU,
	tag_en_BB:          locales.Get_en_BB,
	tag_en_BE:          locales.Get_en_BE,
	tag_en_BI:          locales.Get_en_BI,
	tag_en_BM:          locales.Get_en_BM,
	tag_en_BS:          locales.Get_en_BS,
	tag_en_BW:          locales.Get_en_BW,
	tag_en_BZ:          locales.Get_en_BZ,
	tag_en_CA:          locales.Get_en_CA,
	tag_en_CC:          locales.Get_en_CC,
	tag_en_CH:          locales.Get_en_CH,
	tag_en_CK:          locales.Get_en_CK,
	tag_en_CM:          locales.Get_en_CM,
	tag_en_CX:          locales.Get_en_CX,
	tag_en_CY:          locales.Get_en_CY,
	tag_en_DE:          locales.Get_en_DE,
	tag_en_DG:          locales.Get_en_DG,
	tag_en_DK:          locales.Get_en_DK,
	tag_en_DM:          locales.Get_en_DM,
	tag_en_ER:          locales.Get_en_ER,
	tag_en_FI:          locales.Get_en_FI,
	tag_en_FJ:          locales.Get_en_FJ,
	tag_en_FK:          locales.Get_en_FK,
	tag_en_FM:          locales.Get_en_FM,
	tag_en_GB:          locales.Get_en_GB,
	tag_en_GD:          locales.Get_en_GD,
	tag_en_GG:          locales.Get_en_GG,
	tag_en_GH:          locales.Get_en_GH,
	tag_en_GI:          locales.Get_en_GI,
	tag_en_GM:          locales.Get_en_GM,
	tag_en_GU:          locales.Get_en_GU,
	tag_en_GY:          locales.Get_en_GY,
	tag_en_HK:          locales.Get_en_HK,
	tag_en_IE:          locales.Get_en_IE,
	tag_en_IL:          locales.Get_en_IL,
	tag_en_IM:          locales.Get_en_IM,
	tag_en_IN:          locales.Get_en_IN,
	tag_en_IO:          locales.Get_en_IO,
	tag_en_JE:          locales.Get_en_JE,
	tag_en_JM:          locales.Get_en_JM,
	tag_en_KE:          locales.Get_en_KE,
	tag_en_KI:          locales.Get_en_KI,
	tag_en_KN:          locales.Get_en_KN,
	tag_en_KY:          locales.Get_en_KY,
	tag_en_LC:          locales.Get_en_LC,
	tag_en_LR:          locales.Get_en_LR,
	tag_en_LS:          locales.Get_en_LS,
	tag_en_MG:          locales.Get_en_MG,
	tag_en_MH:          locales.Get_en_MH,
	tag_en_MO:          locales.Get_en_MO,
	tag_en_MP:          locales.Get_en_MP,
	tag_en_MS:          locales.Get_en_MS,
	tag_en_MT:          locales.Get_en_MT,
	tag_en_MU:          locales.Get_en_MU,
	tag_en_MW:          locales.Get_en_MW,
	tag_en_MY:          locales.Get_en_MY,
	tag_en_NA:          locales.Get_en_NA,
	tag_en_NF:          locales.Get_en_NF,
	tag_en_NG:          locales.Get_en_NG,
	tag_en_NL:          locales.Get_en_NL,
	tag_en_NR:          locales.Get_en_NR,
	tag_en_NU:          locales.Get_en_NU,
	tag_en_NZ:          locales.Get_en_NZ,
	tag_en_PG:          locales.Get_en_PG,
	tag_en_PH:          locales.Get_en_PH,
	tag_en_PK:          locales.Get_en_PK,
	tag_en_PN:          locales.Get_en_PN,
	tag_en_PR:          locales.Get_en_PR,
	tag_en_PW:          locales.Get_en_PW,
	tag_en_RW:          locales.Get_en_RW,
	tag_en_SB:          locales.Get_en_SB,
	tag_en_SC:          locales.Get_en_SC,
	tag_en_SD:          locales.Get_en_SD,
	tag_en_SE:          locales.Get_en_SE,
	tag_en_SG:          locales.Get_en_SG,
	tag_en_SH:          locales.Get_en_SH,
	tag_en_SI:          locales.Get_en_SI,
	tag_en_SL:          locales.Get_en_SL,
	tag_en_SS:          locales.Get_en_SS,
	tag_en_SX:          locales.Get_en_SX,
	tag_en_SZ:          locales.Get_en_SZ,
	tag_en_TC:          locales.Get_en_TC,
	tag_en_TK:          locales.Get_en_TK,
	tag_en_TO:          locales.Get_en_TO,
	tag_en_TT:          locales.Get_en_TT,
	tag_en_TV:          locales.Get_en_TV,
	tag_en_TZ:          locales.Get_en_TZ,
	tag_en_UG:          locales.Get_en_UG,
	tag_en_UM:          locales.Get_en_UM,
	tag_en_US:          locales.Get_en_US,
	tag_en_US_POSIX:    locales.Get_en_US_POSIX,
	tag_en_VC:          locales.Get_en_VC,
	tag_en_VG:          locales.Get_en_VG,
	tag_en_VI:          locales.Get_en_VI,
	tag_en_VU:          locales.Get_en_VU,
	tag_en_WS:          locales.Get_en_WS,
	tag_en_ZA:          locales.Get_en_ZA,
	tag_en_ZM:          locales.Get_en_ZM,
	tag_en_ZW:          locales.Get_en_ZW,
	tag_eo:             locales.Get_eo,
	tag_eo_001:         locales.Get_eo_001,
	tag_es:             locales.Get_es,
	tag_es_419:         locales.Get_es_419,
	tag_es_AR:          locales.Get_es_AR,
	tag_es_BO:          locales.Get_es_BO,
	tag_es_BR:          locales.Get_es_BR,
	tag_es_BZ:          locales.Get_es_BZ,
	tag_es_CL:          locales.Get_es_CL,
	tag_es_CO:          locales.Get_es_CO,
	tag_es_CR:          locales.Get_es_CR,
	tag_es_CU:          locales.Get_es_CU,
	tag_es_DO:          locales.Get_es_DO,
	tag_es_EA:          locales.Get_es_EA,
	tag_es_EC:          locales.Get_es_EC,
	tag_es_ES:          locales.Get_es_ES,
	tag_es_GQ:          locales.Get_es_GQ,
	tag_es_GT:          locales.Get_es_GT,
	tag_es_HN:          locales.Get_es_HN,
	tag_es_IC:          locales.Get_es_IC,
	tag_es_MX:          locales.Get_es_MX,
	tag_es_NI:          locales.Get_es_NI,
	tag_es_PA:          locales.Get_es_PA,
	tag_es_PE:          locales.Get_es_PE,
	tag_es_PH:          locales.Get_es_PH,
	tag_es_PR:          locales.Get_es_PR,
	tag_es_PY:          locales.Get_es_PY,
	tag_es_SV:          locales.Get_es_SV,
	tag_es_US:          locales.Get_es_US,
	tag_es_UY:          locales.Get_es_UY,
	tag_es_VE:          locales.Get_es_VE,
	tag_et:             locales.Get_et,
	tag_et_EE:          locales.Get_et_EE,
	tag_eu:             locales.Get_eu,
	tag_eu_ES:          locales.Get_eu_ES,
	tag_ewo:            locales.Get_ewo,
	tag_ewo_CM:         locales.Get_ewo_CM,
	tag_fa:             locales.Get_fa,
	tag_fa_AF:          locales.Get_fa_AF,
	tag_fa_IR:          locales.Get_fa_IR,
	tag_ff:             locales.Get_ff,
	tag_ff_Adlm:        locales.Get_ff_Adlm,
	tag_ff_Adlm_BF:     locales.Get_ff_Adlm_BF,
	tag_ff_Adlm_CM:     locales.Get_ff_Adlm_CM,
	tag_ff_Adlm_GH:     locales.Get_ff_Adlm_GH,
	tag_ff_Adlm_GM:     locales.Get_ff_Adlm_GM,
	tag_ff_Adlm_GN:     locales.Get_ff_Adlm_GN,
	tag_ff_Adlm_GW:     locales.Get_ff_Adlm_GW,
	tag_ff_Adlm_LR:     locales.Get_ff_Adlm_LR,
	tag_ff_Adlm_MR:     locales.Get_ff_Adlm_MR,
	tag_ff_Adlm_NE:     locales.Get_ff_Adlm_NE,
	tag_ff_Adlm_NG:     locales.Get_ff_Adlm_NG,
	tag_ff_Adlm_SL:     locales.Get_ff_Adlm_SL,
	tag_ff_Adlm_SN:     locales.Get_ff_Adlm_SN,
	tag_ff_Latn:        locales.Get_ff_Latn,
	tag_ff_Latn_BF:     locales.Get_ff_Latn_BF,
	tag_ff_Latn_CM:     locales.Get_ff_Latn_CM,
	tag_ff_Latn_GH:     locales.Get_ff_Latn_GH,
	tag_ff_Latn_GM:     locales.Get_ff_Latn_GM,
	tag_ff_Latn_GN:     locales.Get_ff_Latn_GN,
	tag_ff_Latn_GW:     locales.Get_ff_Latn_GW,
	tag_ff_Latn_LR:     locales.Get_ff_Latn_LR,
	tag_ff_Latn_MR:     locales.Get_ff_Latn_MR,
	tag_ff_Latn_NE:     locales.Get_ff_Latn_NE,
	tag_ff_Latn_NG:     locales.Get_ff_Latn_NG,
	tag_ff_Latn_SL:     locales.Get_ff_Latn_SL,
	tag_ff_Latn_SN:     locales.Get_ff_Latn_SN,
	tag_fi:             locales.Get_fi,
	tag_fi_FI:          locales.Get_fi_FI,
	tag_fil:            locales.Get_fil,
	tag_fil_PH:         locales.Get_fil_PH,
	tag_fo:             locales.Get_fo,
	tag_fo_DK:          locales.Get_fo_DK,
	tag_fo_FO:          locales.Get_fo_FO,
	tag_fr:             locales.Get_fr,
	tag_fr_BE:          locales.Get_fr_BE,
	tag_fr_BF:          locales.Get_fr_BF,
	tag_fr_BI:          locales.Get_fr_BI,
	tag_fr_BJ:          locales.Get_fr_BJ,
	tag_fr_BL:          locales.Get_fr_BL,
	tag_fr_CA:          locales.Get_fr_CA,
	tag_fr_CD:          locales.Get_fr_CD,
	tag_fr_CF:          locales.Get_fr_CF,
	tag_fr_CG:          locales.Get_fr_CG,
	tag_fr_CH:          locales.Get_fr_CH,
	tag_fr_CI:          locales.Get_fr_CI,
	tag_fr_CM:          locales.Get_fr_CM,
	tag_fr_DJ:          locales.Get_fr_DJ,
	tag_fr_DZ:          locales.Get_fr_DZ,
	tag_fr_FR:          locales.Get_fr_FR,
	tag_fr_GA:          locales.Get_fr_GA,
	tag_fr_GF:          locales.Get_fr_GF,
	tag_fr_GN:          locales.Get_fr_GN,
	tag_fr_GP:          locales.Get_fr_GP,
	tag_fr_GQ:          locales.Get_fr_GQ,
	tag_fr_HT:          locales.Get_fr_HT,
	tag_fr_KM:          locales.Get_fr_KM,
	tag_fr_LU:          locales.Get_fr_LU,
	tag_fr_MA:          locales.Get_fr_MA,
	tag_fr_MC:          locales.Get_fr_MC,
	tag_fr_MF:          locales.Get_fr_MF,
	tag_fr_MG:          locales.Get_fr_MG,
	tag_fr_ML:          locales.Get_fr_ML,
	tag_fr_MQ:          locales.Get_fr_MQ,
	tag_fr_MR:          locales.Get_fr_MR,
	tag_fr_MU:          locales.Get_fr_MU,
	tag_fr_NC:          locales.Get_fr_NC,
	tag_fr_NE:          locales.Get_fr_NE,
	tag_fr_PF:          locales.Get_fr_PF,
	tag_fr_PM:          locales.Get_fr_PM,
	tag_fr_RE:          locales.Get_fr_RE,
	tag_fr_RW:          locales.Get_fr_RW,
	tag_fr_SC:          locales.Get_fr_SC,
	tag_fr_SN:          locales.Get_fr_SN,
	tag_fr_SY:          locales.Get_fr_SY,
	tag_fr_TD:          locales.Get_fr_TD,
	tag_fr_TG:          locales.Get_fr_TG,
	tag_fr_TN:          locales.Get_fr_TN,
	tag_fr_VU:          locales.Get_fr_VU,
	tag_fr_WF:          locales.Get_fr_WF,
	tag_fr_YT:          locales.Get_fr_YT,
	tag_fur:            locales.Get_fur,
	tag_fur_IT:         locales.Get_fur_IT,
	tag_fy:             locales.Get_fy,
	tag_fy_NL:          locales.Get_fy_NL,
	tag_ga:             locales.Get_ga,
	tag_ga_GB:          locales.Get_ga_GB,
	tag_ga_IE:          locales.Get_ga_IE,
	tag_gd:             locales.Get_gd,
	tag_gd_GB:          locales.Get_gd_GB,
	tag_gl:             locales.Get_gl,
	tag_gl_ES:          locales.Get_gl_ES,
	tag_gsw:            locales.Get_gsw,
	tag_gsw_CH:         locales.Get_gsw_CH,
	tag_gsw_FR:         locales.Get_gsw_FR,
	tag_gsw_LI:         locales.Get_gsw_LI,
	tag_gu:             locales.Get_gu,
	tag_gu_IN:          locales.Get_gu_IN,
	tag_guz:            locales.Get_guz,
	tag_guz_KE:         locales.Get_guz_KE,
	tag_gv:             locales.Get_gv,
	tag_gv_IM:          locales.Get_gv_IM,
	tag_ha:             locales.Get_ha,
	tag_ha_GH:          locales.Get_ha_GH,
	tag_ha_NE:          locales.Get_ha_NE,
	tag_ha_NG:          locales.Get_ha_NG,
	tag_haw:            locales.Get_haw,
	tag_haw_US:         locales.Get_haw_US,
	tag_he:             locales.Get_he,
	tag_he_IL:          locales.Get_he_IL,
	tag_hi:             locales.Get_hi,
	tag_hi_IN:          locales.Get_hi_IN,
	tag_hr:             locales.Get_hr,
	tag_hr_BA:          locales.Get_hr_BA,
	tag_hr_HR:          locales.Get_hr_HR,
	tag_hsb:            locales.Get_hsb,
	tag_hsb_DE:         locales.Get_hsb_DE,
	tag_hu:             locales.Get_hu,
	tag_hu_HU:          locales.Get_hu_HU,
	tag_hy:             locales.Get_hy,
	tag_hy_AM:          locales.Get_hy_AM,
	tag_ia:             locales.Get_ia,
	tag_ia_001:         locales.Get_ia_001,
	tag_id:             locales.Get_id,
	tag_id_ID:          locales.Get_id_ID,
	tag_ig:             locales.Get_ig,
	tag_ig_NG:          locales.Get_ig_NG,
	tag_ii:             locales.Get_ii,
	tag_ii_CN:          locales.Get_ii_CN,
	tag_is:             locales.Get_is,
	tag_is_IS:          locales.Get_is_IS,
	tag_it:             locales.Get_it,
	tag_it_CH:          locales.Get_it_CH,
	tag_it_IT:          locales.Get_it_IT,
	tag_it_SM:          locales.Get_it_SM,
	tag_it_VA:          locales.Get_it_VA,
	tag_ja:             locales.Get_ja,
	tag_ja_JP:          locales.Get_ja_JP,
	tag_jgo:            locales.Get_jgo,
	tag_jgo_CM:         locales.Get_jgo_CM,
	tag_jmc:            locales.Get_jmc,
	tag_jmc_TZ:         locales.Get_jmc_TZ,
	tag_jv:             locales.Get_jv,
	tag_jv_ID:          locales.Get_jv_ID,
	tag_ka:             locales.Get_ka,
	tag_ka_GE:          locales.Get_ka_GE,
	tag_kab:            locales.Get_kab,
	tag_kab_DZ:         locales.Get_kab_DZ,
	tag_kam:            locales.Get_kam,
	tag_kam_KE:         locales.Get_kam_KE,
	tag_kde:            locales.Get_kde,
	tag_kde_TZ:         locales.Get_kde_TZ,
	tag_kea:            locales.Get_kea,
	tag_kea_CV:         locales.Get_kea_CV,
	tag_khq:            locales.Get_khq,
	tag_khq_ML:         locales.Get_khq_ML,
	tag_ki:             locales.Get_ki,
	tag_ki_KE:          locales.Get_ki_KE,
	tag_kk:             locales.Get_kk,
	tag_kk_KZ:          locales.Get_kk_KZ,
	tag_kkj:            locales.Get_kkj,
	tag_kkj_CM:         locales.Get_kkj_CM,
	tag_kl:             locales.Get_kl,
	tag_kl_GL:          locales.Get_kl_GL,
	tag_kln:            locales.Get_kln,
	tag_kln_KE:         locales.Get_kln_KE,
	tag_km:             locales.Get_km,
	tag_km_KH:          locales.Get_km_KH,
	tag_kn:             locales.Get_kn,
	tag_kn_IN:          locales.Get_kn_IN,
	tag_ko:             locales.Get_ko,
	tag_ko_KP:          locales.Get_ko_KP,
	tag_ko_KR:          locales.Get_ko_KR,
	tag_kok:            locales.Get_kok,
	tag_kok_IN:         locales.Get_kok_IN,
	tag_ks:             locales.Get_ks,
	tag_ks_Arab:        locales.Get_ks_Arab,
	tag_ks_Arab_IN:     locales.Get_ks_Arab_IN,
	tag_ksb:            locales.Get_ksb,
	tag_ksb_TZ:         locales.Get_ksb_TZ,
	tag_ksf:            locales.Get_ksf,
	tag_ksf_CM:         locales.Get_ksf_CM,
	tag_ksh:            locales.Get_ksh,
	tag_ksh_DE:         locales.Get_ksh_DE,
	tag_ku:             locales.Get_ku,
	tag_ku_TR:          locales.Get_ku_TR,
	tag_kw:             locales.Get_kw,
	tag_kw_GB:          locales.Get_kw_GB,
	tag_ky:             locales.Get_ky,
	tag_ky_KG:          locales.Get_ky_KG,
	tag_lag:            locales.Get_lag,
	tag_lag_TZ:         locales.Get_lag_TZ,
	tag_lb:             locales.Get_lb,
	tag_lb_LU:          locales.Get_lb_LU,
	tag_lg:             locales.Get_lg,
	tag_lg_UG:          locales.Get_lg_UG,
	tag_lkt:            locales.Get_lkt,
	tag_lkt_US:         locales.Get_lkt_US,
	tag_ln:             locales.Get_ln,
	tag_ln_AO:          locales.Get_ln_AO,
	tag_ln_CD:          locales.Get_ln_CD,
	tag_ln_CF:          locales.Get_ln_CF,
	tag_ln_CG:          locales.Get_ln_CG,
	tag_lo:             locales.Get_lo,
	tag_lo_LA:          locales.Get_lo_LA,
	tag_lrc:            locales.Get_lrc,
	tag_lrc_IQ:         locales.Get_lrc_IQ,
	tag_lrc_IR:         locales.Get_lrc_IR,
	tag_lt:             locales.Get_lt,
	tag_lt_LT:          locales.Get_lt_LT,
	tag_lu:             locales.Get_lu,
	tag_lu_CD:          locales.Get_lu_CD,
	tag_luo:            locales.Get_luo,
	tag_luo_KE:         locales.Get_luo_KE,
	tag_luy:            locales.Get_luy,
	tag_luy_KE:         locales.Get_luy_KE,
	tag_lv:             locales.Get_lv,
	tag_lv_LV:          locales.Get_lv_LV,
	tag_mai:            locales.Get_mai,
	tag_mai_IN:         locales.Get_mai_IN,
	tag_mas:            locales.Get_mas,
	tag_mas_KE:         locales.Get_mas_KE,
	tag_mas_TZ:         locales.Get_mas_TZ,
	tag_mer:            locales.Get_mer,
	tag_mer_KE:         locales.Get_mer_KE,
	tag_mfe:            locales.Get_mfe,
	tag_mfe_MU:         locales.Get_mfe_MU,
	tag_mg:             locales.Get_mg,
	tag_mg_MG:          locales.Get_mg_MG,
	tag_mgh:            locales.Get_mgh,
	tag_mgh_MZ:         locales.Get_mgh_MZ,
	tag_mgo:            locales.Get_mgo,
	tag_mgo_CM:         locales.Get_mgo_CM,
	tag_mi:             locales.Get_mi,
	tag_mi_NZ:          locales.Get_mi_NZ,
	tag_mk:             locales.Get_mk,
	tag_mk_MK:          locales.Get_mk_MK,
	tag_ml:             locales.Get_ml,
	tag_ml_IN:          locales.Get_ml_IN,
	tag_mn:             locales.Get_mn,
	tag_mn_MN:          locales.Get_mn_MN,
	tag_mni:            locales.Get_mni,
	tag_mni_Beng:       locales.Get_mni_Beng,
	tag_mni_Beng_IN:    locales.Get_mni_Beng_IN,
	tag_mr:             locales.Get_mr,
	tag_mr_IN:          locales.Get_mr_IN,
	tag_ms:             locales.Get_ms,
	tag_ms_BN:          locales.Get_ms_BN,
	tag_ms_ID:          locales.Get_ms_ID,
	tag_ms_MY:          locales.Get_ms_MY,
	tag_ms_SG:          locales.Get_ms_SG,
	tag_mt:             locales.Get_mt,
	tag_mt_MT:          locales.Get_mt_MT,
	tag_mua:            locales.Get_mua,
	tag_mua_CM:         locales.Get_mua_CM,
	tag_my:             locales.Get_my,
	tag_my_MM:          locales.Get_my_MM,
	tag_mzn:            locales.Get_mzn,
	tag_mzn_IR:         locales.Get_mzn_IR,
	tag_naq:            locales.Get_naq,
	tag_naq_NA:         locales.Get_naq_NA,
	tag_nb:             locales.Get_nb,
	tag_nb_NO:          locales.Get_nb_NO,
	tag_nb_SJ:          locales.Get_nb_SJ,
	tag_nd:             locales.Get_nd,
	tag_nd_ZW:          locales.Get_nd_ZW,
	tag_nds:            locales.Get_nds,
	tag_nds_DE:         locales.Get_nds_DE,
	tag_nds_NL:         locales.Get_nds_NL,
	tag_ne:             locales.Get_ne,
	tag_ne_IN:          locales.Get_ne_IN,
	tag_ne_NP:          locales.Get_ne_NP,
	tag_nl:             locales.Get_nl,
	tag_nl_AW:          locales.Get_nl_AW,
	tag_nl_BE:          locales.Get_nl_BE,
	tag_nl_BQ:          locales.Get_nl_BQ,
	tag_nl_CW:          locales.Get_nl_CW,
	tag_nl_NL:          locales.Get_nl_NL,
	tag_nl_SR:          locales.Get_nl_SR,
	tag_nl_SX:          locales.Get_nl_SX,
	tag_nmg:            locales.Get_nmg,
	tag_nmg_CM:         locales.Get_nmg_CM,
	tag_nn:             locales.Get_nn,
	tag_nn_NO:          locales.Get_nn_NO,
	tag_nnh:            locales.Get_nnh,
	tag_nnh_CM:         locales.Get_nnh_CM,
	tag_nus:            locales.Get_nus,
	tag_nus_SS:         locales.Get_nus_SS,
	tag_nyn:            locales.Get_nyn,
	tag_nyn_UG:         locales.Get_nyn_UG,
	tag_om:             locales.Get_om,
	tag_om_ET:          locales.Get_om_ET,
	tag_om_KE:          locales.Get_om_KE,
	tag_or:             locales.Get_or,
	tag_or_IN:          locales.Get_or_IN,
	tag_os:             locales.Get_os,
	tag_os_GE:          locales.Get_os_GE,
	tag_os_RU:          locales.Get_os_RU,
	tag_pa:             locales.Get_pa,
	tag_pa_Arab:        locales.Get_pa_Arab,
	tag_pa_Arab_PK:     locales.Get_pa_Arab_PK,
	tag_pa_Guru:        locales.Get_pa_Guru,
	tag_pa_Guru_IN:     locales.Get_pa_Guru_IN,
	tag_pcm:            locales.Get_pcm,
	tag_pcm_NG:         locales.Get_pcm_NG,
	tag_pl:             locales.Get_pl,
	tag_pl_PL:          locales.Get_pl_PL,
	tag_prg:            locales.Get_prg,
	tag_prg_001:        locales.Get_prg_001,
	tag_ps:             locales.Get_ps,
	tag_ps_AF:          locales.Get_ps_AF,
	tag_ps_PK:          locales.Get_ps_PK,
	tag_pt:             locales.Get_pt,
	tag_pt_AO:          locales.Get_pt_AO,
	tag_pt_BR:          locales.Get_pt_BR,
	tag_pt_CH:          locales.Get_pt_CH,
	tag_pt_CV:          locales.Get_pt_CV,
	tag_pt_GQ:          locales.Get_pt_GQ,
	tag_pt_GW:          locales.Get_pt_GW,
	tag_pt_LU:          locales.Get_pt_LU,
	tag_pt_MO:          locales.Get_pt_MO,
	tag_pt_MZ:          locales.Get_pt_MZ,
	tag_pt_PT:          locales.Get_pt_PT,
	tag_pt_ST:          locales.Get_pt_ST,
	tag_pt_TL:          locales.Get_pt_TL,
	tag_qu:             locales.Get_qu,
	tag_qu_BO:          locales.Get_qu_BO,
	tag_qu_EC:          locales.Get_qu_EC,
	tag_qu_PE:          locales.Get_qu_PE,
	tag_rm:             locales.Get_rm,
	tag_rm_CH:          locales.Get_rm_CH,
	tag_rn:             locales.Get_rn,
	tag_rn_BI:          locales.Get_rn_BI,
	tag_ro:             locales.Get_ro,
	tag_ro_MD:          locales.Get_ro_MD,
	tag_ro_RO:          locales.Get_ro_RO,
	tag_rof:            locales.Get_rof,
	tag_rof_TZ:         locales.Get_rof_TZ,
	tag_root:           locales.Get_root,
	tag_ru:             locales.Get_ru,
	tag_ru_BY:          locales.Get_ru_BY,
	tag_ru_KG:          locales.Get_ru_KG,
	tag_ru_KZ:          locales.Get_ru_KZ,
	tag_ru_MD:          locales.Get_ru_MD,
	tag_ru_RU:          locales.Get_ru_RU,
	tag_ru_UA:          locales.Get_ru_UA,
	tag_rw:             locales.Get_rw,
	tag_rw_RW:          locales.Get_rw_RW,
	tag_rwk:            locales.Get_rwk,
	tag_rwk_TZ:         locales.Get_rwk_TZ,
	tag_sah:            locales.Get_sah,
	tag_sah_RU:         locales.Get_sah_RU,
	tag_saq:            locales.Get_saq,
	tag_saq_KE:         locales.Get_saq_KE,
	tag_sat:            locales.Get_sat,
	tag_sat_Olck:       locales.Get_sat_Olck,
	tag_sat_Olck_IN:    locales.Get_sat_Olck_IN,
	tag_sbp:            locales.Get_sbp,
	tag_sbp_TZ:         locales.Get_sbp_TZ,
	tag_sd:             locales.Get_sd,
	tag_sd_Arab:        locales.Get_sd_Arab,
	tag_sd_Arab_PK:     locales.Get_sd_Arab_PK,
	tag_sd_Deva:        locales.Get_sd_Deva,
	tag_sd_Deva_IN:     locales.Get_sd_Deva_IN,
	tag_se:             locales.Get_se,
	tag_se_FI:          locales.Get_se_FI,
	tag_se_NO:          locales.Get_se_NO,
	tag_se_SE:          locales.Get_se_SE,
	tag_seh:            locales.Get_seh,
	tag_seh_MZ:         locales.Get_seh_MZ,
	tag_ses:            locales.Get_ses,
	tag_ses_ML:         locales.Get_ses_ML,
	tag_sg:             locales.Get_sg,
	tag_sg_CF:          locales.Get_sg_CF,
	tag_shi:            locales.Get_shi,
	tag_shi_Latn:       locales.Get_shi_Latn,
	tag_shi_Latn_MA:    locales.Get_shi_Latn_MA,
	tag_shi_Tfng:       locales.Get_shi_Tfng,
	tag_shi_Tfng_MA:    locales.Get_shi_Tfng_MA,
	tag_si:             locales.Get_si,
	tag_si_LK:          locales.Get_si_LK,
	tag_sk:             locales.Get_sk,
	tag_sk_SK:          locales.Get_sk_SK,
	tag_sl:             locales.Get_sl,
	tag_sl_SI:          locales.Get_sl_SI,
	tag_smn:            locales.Get_smn,
	tag_smn_FI:         locales.Get_smn_FI,
	tag_sn:             locales.Get_sn,
	tag_sn_ZW:          locales.Get_sn_ZW,
	tag_so:             locales.Get_so,
	tag_so_DJ:          locales.Get_so_DJ,
	tag_so_ET:          locales.Get_so_ET,
	tag_so_KE:          locales.Get_so_KE,
	tag_so_SO:          locales.Get_so_SO,
	tag_sq:             locales.Get_sq,
	tag_sq_AL:          locales.Get_sq_AL,
	tag_sq_MK:          locales.Get_sq_MK,
	tag_sq_XK:          locales.Get_sq_XK,
	tag_sr:             locales.Get_sr,
	tag_sr_Cyrl:        locales.Get_sr_Cyrl,
	tag_sr_Cyrl_BA:     locales.Get_sr_Cyrl_BA,
	tag_sr_Cyrl_ME:     locales.Get_sr_Cyrl_ME,
	tag_sr_Cyrl_RS:     locales.Get_sr_Cyrl_RS,
	tag_sr_Cyrl_XK:     locales.Get_sr_Cyrl_XK,
	tag_sr_Latn:        locales.Get_sr_Latn,
	tag_sr_Latn_BA:     locales.Get_sr_Latn_BA,
	tag_sr_Latn_ME:     locales.Get_sr_Latn_ME,
	tag_sr_Latn_RS:     locales.Get_sr_Latn_RS,
	tag_sr_Latn_XK:     locales.Get_sr_Latn_XK,
	tag_su:             locales.Get_su,
	tag_su_Latn:        locales.Get_su_Latn,
	tag_su_Latn_ID:     locales.Get_su_Latn_ID,
	tag_sv:             locales.Get_sv,
	tag_sv_AX:          locales.Get_sv_AX,
	tag_sv_FI:          locales.Get_sv_FI,
	tag_sv_SE:          locales.Get_sv_SE,
	tag_sw:             locales.Get_sw,
	tag_sw_CD:          locales.Get_sw_CD,
	tag_sw_KE:          locales.Get_sw_KE,
	tag_sw_TZ:          locales.Get_sw_TZ,
	tag_sw_UG:          locales.Get_sw_UG,
	tag_ta:             locales.Get_ta,
	tag_ta_IN:          locales.Get_ta_IN,
	tag_ta_LK:          locales.Get_ta_LK,
	tag_ta_MY:          locales.Get_ta_MY,
	tag_ta_SG:          locales.Get_ta_SG,
	tag_te:             locales.Get_te,
	tag_te_IN:          locales.Get_te_IN,
	tag_teo:            locales.Get_teo,
	tag_teo_KE:         locales.Get_teo_KE,
	tag_teo_UG:         locales.Get_teo_UG,
	tag_tg:             locales.Get_tg,
	tag_tg_TJ:          locales.Get_tg_TJ,
	tag_th:             locales.Get_th,
	tag_th_TH:          locales.Get_th_TH,
	tag_ti:             locales.Get_ti,
	tag_ti_ER:          locales.Get_ti_ER,
	tag_ti_ET:          locales.Get_ti_ET,
	tag_tk:             locales.Get_tk,
	tag_tk_TM:          locales.Get_tk_TM,
	tag_to:             locales.Get_to,
	tag_to_TO:          locales.Get_to_TO,
	tag_tr:             locales.Get_tr,
	tag_tr_CY:          locales.Get_tr_CY,
	tag_tr_TR:          locales.Get_tr_TR,
	tag_tt:             locales.Get_tt,
	tag_tt_RU:          locales.Get_tt_RU,
	tag_twq:            locales.Get_twq,
	tag_twq_NE:         locales.Get_twq_NE,
	tag_tzm:            locales.Get_tzm,
	tag_tzm_MA:         locales.Get_tzm_MA,
	tag_ug:             locales.Get_ug,
	tag_ug_CN:          locales.Get_ug_CN,
	tag_uk:             locales.Get_uk,
	tag_uk_UA:          locales.Get_uk_UA,
	tag_ur:             locales.Get_ur,
	tag_ur_IN:          locales.Get_ur_IN,
	tag_ur_PK:          locales.Get_ur_PK,
	tag_uz:             locales.Get_uz,
	tag_uz_Arab:        locales.Get_uz_Arab,
	tag_uz_Arab_AF:     locales.Get_uz_Arab_AF,
	tag_uz_Cyrl:        locales.Get_uz_Cyrl,
	tag_uz_Cyrl_UZ:     locales.Get_uz_Cyrl_UZ,
	tag_uz_Latn:        locales.Get_uz_Latn,
	tag_uz_Latn_UZ:     locales.Get_uz_Latn_UZ,
	tag_vai:            locales.Get_vai,
	tag_vai_Latn:       locales.Get_vai_Latn,
	tag_vai_Latn_LR:    locales.Get_vai_Latn_LR,
	tag_vai_Vaii:       locales.Get_vai_Vaii,
	tag_vai_Vaii_LR:    locales.Get_vai_Vaii_LR,
	tag_vi:             locales.Get_vi,
	tag_vi_VN:          locales.Get_vi_VN,
	tag_vo:             locales.Get_vo,
	tag_vo_001:         locales.Get_vo_001,
	tag_vun:            locales.Get_vun,
	tag_vun_TZ:         locales.Get_vun_TZ,
	tag_wae:            locales.Get_wae,
	tag_wae_CH:         locales.Get_wae_CH,
	tag_wo:             locales.Get_wo,
	tag_wo_SN:          locales.Get_wo_SN,
	tag_xh:             locales.Get_xh,
	tag_xh_ZA:          locales.Get_xh_ZA,
	tag_xog:            locales.Get_xog,
	tag_xog_UG:         locales.Get_xog_UG,
	tag_yav:            locales.Get_yav,
	tag_yav_CM:         locales.Get_yav_CM,
	tag_yi:             locales.Get_yi,
	tag_yi_001:         locales.Get_yi_001,
	tag_yo:             locales.Get_yo,
	tag_yo_BJ:          locales.Get_yo_BJ,
	tag_yo_NG:          locales.Get_yo_NG,
	tag_yue:            locales.Get_yue,
	tag_yue_Hans:       locales.Get_yue_Hans,
	tag_yue_Hans_CN:    locales.Get_yue_Hans_CN,
	tag_yue_Hant:       locales.Get_yue_Hant,
	tag_yue_Hant_HK:    locales.Get_yue_Hant_HK,
	tag_zgh:            locales.Get_zgh,
	tag_zgh_MA:         locales.Get_zgh_MA,
	tag_zh:             locales.Get_zh,
	tag_zh_Hans:        locales.Get_zh_Hans,
	tag_zh_Hans_CN:     locales.Get_zh_Hans_CN,
	tag_zh_Hans_HK:     locales.Get_zh_Hans_HK,
	tag_zh_Hans_MO:     locales.Get_zh_Hans_MO,
	tag_zh_Hans_SG:     locales.Get_zh_Hans_SG,
	tag_zh_Hant:        locales.Get_zh_Hant,
	tag_zh_Hant_HK:     locales.Get_zh_Hant_HK,
	tag_zh_Hant_MO:     locales.Get_zh_Hant_MO,
	tag_zh_Hant_TW:     locales.Get_zh_Hant_TW,
	tag_zu:             locales.Get_zu,
	tag_zu_ZA:          locales.Get_zu_ZA,
}

var tag_af = language.Make("af")
var tag_af_NA = language.Make("af_NA")
var tag_af_ZA = language.Make("af_ZA")
var tag_agq = language.Make("agq")
var tag_agq_CM = language.Make("agq_CM")
var tag_ak = language.Make("ak")
var tag_ak_GH = language.Make("ak_GH")
var tag_am = language.Make("am")
var tag_am_ET = language.Make("am_ET")
var tag_an = language.Make("an")
var tag_ar = language.Make("ar")
var tag_ar_001 = language.Make("ar_001")
var tag_ar_AE = language.Make("ar_AE")
var tag_ar_BH = language.Make("ar_BH")
var tag_ar_DJ = language.Make("ar_DJ")
var tag_ar_DZ = language.Make("ar_DZ")
var tag_ar_EG = language.Make("ar_EG")
var tag_ar_EH = language.Make("ar_EH")
var tag_ar_ER = language.Make("ar_ER")
var tag_ar_IL = language.Make("ar_IL")
var tag_ar_IQ = language.Make("ar_IQ")
var tag_ar_JO = language.Make("ar_JO")
var tag_ar_KM = language.Make("ar_KM")
var tag_ar_KW = language.Make("ar_KW")
var tag_ar_LB = language.Make("ar_LB")
var tag_ar_LY = language.Make("ar_LY")
var tag_ar_MA = language.Make("ar_MA")
var tag_ar_MR = language.Make("ar_MR")
var tag_ar_OM = language.Make("ar_OM")
var tag_ar_PS = language.Make("ar_PS")
var tag_ar_QA = language.Make("ar_QA")
var tag_ar_SA = language.Make("ar_SA")
var tag_ar_SD = language.Make("ar_SD")
var tag_ar_SO = language.Make("ar_SO")
var tag_ar_SS = language.Make("ar_SS")
var tag_ar_SY = language.Make("ar_SY")
var tag_ar_TD = language.Make("ar_TD")
var tag_ar_TN = language.Make("ar_TN")
var tag_ar_YE = language.Make("ar_YE")
var tag_ars = language.Make("ars")
var tag_as = language.Make("as")
var tag_as_IN = language.Make("as_IN")
var tag_asa = language.Make("asa")
var tag_asa_TZ = language.Make("asa_TZ")
var tag_ast = language.Make("ast")
var tag_ast_ES = language.Make("ast_ES")
var tag_az = language.Make("az")
var tag_az_Cyrl = language.Make("az_Cyrl")
var tag_az_Cyrl_AZ = language.Make("az_Cyrl_AZ")
var tag_az_Latn = language.Make("az_Latn")
var tag_az_Latn_AZ = language.Make("az_Latn_AZ")
var tag_bas = language.Make("bas")
var tag_bas_CM = language.Make("bas_CM")
var tag_be = language.Make("be")
var tag_be_BY = language.Make("be_BY")
var tag_bem = language.Make("bem")
var tag_bem_ZM = language.Make("bem_ZM")
var tag_bez = language.Make("bez")
var tag_bez_TZ = language.Make("bez_TZ")
var tag_bg = language.Make("bg")
var tag_bg_BG = language.Make("bg_BG")
var tag_bho = language.Make("bho")
var tag_bm = language.Make("bm")
var tag_bm_ML = language.Make("bm_ML")
var tag_bn = language.Make("bn")
var tag_bn_BD = language.Make("bn_BD")
var tag_bn_IN = language.Make("bn_IN")
var tag_bo = language.Make("bo")
var tag_bo_CN = language.Make("bo_CN")
var tag_bo_IN = language.Make("bo_IN")
var tag_br = language.Make("br")
var tag_br_FR = language.Make("br_FR")
var tag_brx = language.Make("brx")
var tag_brx_IN = language.Make("brx_IN")
var tag_bs = language.Make("bs")
var tag_bs_Cyrl = language.Make("bs_Cyrl")
var tag_bs_Cyrl_BA = language.Make("bs_Cyrl_BA")
var tag_bs_Latn = language.Make("bs_Latn")
var tag_bs_Latn_BA = language.Make("bs_Latn_BA")
var tag_ca = language.Make("ca")
var tag_ca_AD = language.Make("ca_AD")
var tag_ca_ES = language.Make("ca_ES")
var tag_ca_ES_VALENCIA = language.Make("ca_ES_VALENCIA")
var tag_ca_FR = language.Make("ca_FR")
var tag_ca_IT = language.Make("ca_IT")
var tag_ccp = language.Make("ccp")
var tag_ccp_BD = language.Make("ccp_BD")
var tag_ccp_IN = language.Make("ccp_IN")
var tag_ce = language.Make("ce")
var tag_ce_RU = language.Make("ce_RU")
var tag_ceb = language.Make("ceb")
var tag_ceb_PH = language.Make("ceb_PH")
var tag_cgg = language.Make("cgg")
var tag_cgg_UG = language.Make("cgg_UG")
var tag_chr = language.Make("chr")
var tag_chr_US = language.Make("chr_US")
var tag_ckb = language.Make("ckb")
var tag_ckb_IQ = language.Make("ckb_IQ")
var tag_ckb_IR = language.Make("ckb_IR")
var tag_cs = language.Make("cs")
var tag_cs_CZ = language.Make("cs_CZ")
var tag_cu = language.Make("cu")
var tag_cu_RU = language.Make("cu_RU")
var tag_cy = language.Make("cy")
var tag_cy_GB = language.Make("cy_GB")
var tag_da = language.Make("da")
var tag_da_DK = language.Make("da_DK")
var tag_da_GL = language.Make("da_GL")
var tag_dav = language.Make("dav")
var tag_dav_KE = language.Make("dav_KE")
var tag_de = language.Make("de")
var tag_de_AT = language.Make("de_AT")
var tag_de_BE = language.Make("de_BE")
var tag_de_CH = language.Make("de_CH")
var tag_de_DE = language.Make("de_DE")
var tag_de_IT = language.Make("de_IT")
var tag_de_LI = language.Make("de_LI")
var tag_de_LU = language.Make("de_LU")
var tag_dje = language.Make("dje")
var tag_dje_NE = language.Make("dje_NE")
var tag_dsb = language.Make("dsb")
var tag_dsb_DE = language.Make("dsb_DE")
var tag_dua = language.Make("dua")
var tag_dua_CM = language.Make("dua_CM")
var tag_dv = language.Make("dv")
var tag_dyo = language.Make("dyo")
var tag_dyo_SN = language.Make("dyo_SN")
var tag_dz = language.Make("dz")
var tag_dz_BT = language.Make("dz_BT")
var tag_ebu = language.Make("ebu")
var tag_ebu_KE = language.Make("ebu_KE")
var tag_ee = language.Make("ee")
var tag_ee_GH = language.Make("ee_GH")
var tag_ee_TG = language.Make("ee_TG")
var tag_el = language.Make("el")
var tag_el_CY = language.Make("el_CY")
var tag_el_GR = language.Make("el_GR")
var tag_en = language.Make("en")
var tag_en_001 = language.Make("en_001")
var tag_en_150 = language.Make("en_150")
var tag_en_AE = language.Make("en_AE")
var tag_en_AG = language.Make("en_AG")
var tag_en_AI = language.Make("en_AI")
var tag_en_AS = language.Make("en_AS")
var tag_en_AT = language.Make("en_AT")
var tag_en_AU = language.Make("en_AU")
var tag_en_BB = language.Make("en_BB")
var tag_en_BE = language.Make("en_BE")
var tag_en_BI = language.Make("en_BI")
var tag_en_BM = language.Make("en_BM")
var tag_en_BS = language.Make("en_BS")
var tag_en_BW = language.Make("en_BW")
var tag_en_BZ = language.Make("en_BZ")
var tag_en_CA = language.Make("en_CA")
var tag_en_CC = language.Make("en_CC")
var tag_en_CH = language.Make("en_CH")
var tag_en_CK = language.Make("en_CK")
var tag_en_CM = language.Make("en_CM")
var tag_en_CX = language.Make("en_CX")
var tag_en_CY = language.Make("en_CY")
var tag_en_DE = language.Make("en_DE")
var tag_en_DG = language.Make("en_DG")
var tag_en_DK = language.Make("en_DK")
var tag_en_DM = language.Make("en_DM")
var tag_en_ER = language.Make("en_ER")
var tag_en_FI = language.Make("en_FI")
var tag_en_FJ = language.Make("en_FJ")
var tag_en_FK = language.Make("en_FK")
var tag_en_FM = language.Make("en_FM")
var tag_en_GB = language.Make("en_GB")
var tag_en_GD = language.Make("en_GD")
var tag_en_GG = language.Make("en_GG")
var tag_en_GH = language.Make("en_GH")
var tag_en_GI = language.Make("en_GI")
var tag_en_GM = language.Make("en_GM")
var tag_en_GU = language.Make("en_GU")
var tag_en_GY = language.Make("en_GY")
var tag_en_HK = language.Make("en_HK")
var tag_en_IE = language.Make("en_IE")
var tag_en_IL = language.Make("en_IL")
var tag_en_IM = language.Make("en_IM")
var tag_en_IN = language.Make("en_IN")
var tag_en_IO = language.Make("en_IO")
var tag_en_JE = language.Make("en_JE")
var tag_en_JM = language.Make("en_JM")
var tag_en_KE = language.Make("en_KE")
var tag_en_KI = language.Make("en_KI")
var tag_en_KN = language.Make("en_KN")
var tag_en_KY = language.Make("en_KY")
var tag_en_LC = language.Make("en_LC")
var tag_en_LR = language.Make("en_LR")
var tag_en_LS = language.Make("en_LS")
var tag_en_MG = language.Make("en_MG")
var tag_en_MH = language.Make("en_MH")
var tag_en_MO = language.Make("en_MO")
var tag_en_MP = language.Make("en_MP")
var tag_en_MS = language.Make("en_MS")
var tag_en_MT = language.Make("en_MT")
var tag_en_MU = language.Make("en_MU")
var tag_en_MW = language.Make("en_MW")
var tag_en_MY = language.Make("en_MY")
var tag_en_NA = language.Make("en_NA")
var tag_en_NF = language.Make("en_NF")
var tag_en_NG = language.Make("en_NG")
var tag_en_NL = language.Make("en_NL")
var tag_en_NR = language.Make("en_NR")
var tag_en_NU = language.Make("en_NU")
var tag_en_NZ = language.Make("en_NZ")
var tag_en_PG = language.Make("en_PG")
var tag_en_PH = language.Make("en_PH")
var tag_en_PK = language.Make("en_PK")
var tag_en_PN = language.Make("en_PN")
var tag_en_PR = language.Make("en_PR")
var tag_en_PW = language.Make("en_PW")
var tag_en_RW = language.Make("en_RW")
var tag_en_SB = language.Make("en_SB")
var tag_en_SC = language.Make("en_SC")
var tag_en_SD = language.Make("en_SD")
var tag_en_SE = language.Make("en_SE")
var tag_en_SG = language.Make("en_SG")
var tag_en_SH = language.Make("en_SH")
var tag_en_SI = language.Make("en_SI")
var tag_en_SL = language.Make("en_SL")
var tag_en_SS = language.Make("en_SS")
var tag_en_SX = language.Make("en_SX")
var tag_en_SZ = language.Make("en_SZ")
var tag_en_TC = language.Make("en_TC")
var tag_en_TK = language.Make("en_TK")
var tag_en_TO = language.Make("en_TO")
var tag_en_TT = language.Make("en_TT")
var tag_en_TV = language.Make("en_TV")
var tag_en_TZ = language.Make("en_TZ")
var tag_en_UG = language.Make("en_UG")
var tag_en_UM = language.Make("en_UM")
var tag_en_US = language.Make("en_US")
var tag_en_US_POSIX = language.Make("en_US_POSIX")
var tag_en_VC = language.Make("en_VC")
var tag_en_VG = language.Make("en_VG")
var tag_en_VI = language.Make("en_VI")
var tag_en_VU = language.Make("en_VU")
var tag_en_WS = language.Make("en_WS")
var tag_en_ZA = language.Make("en_ZA")
var tag_en_ZM = language.Make("en_ZM")
var tag_en_ZW = language.Make("en_ZW")
var tag_eo = language.Make("eo")
var tag_eo_001 = language.Make("eo_001")
var tag_es = language.Make("es")
var tag_es_419 = language.Make("es_419")
var tag_es_AR = language.Make("es_AR")
var tag_es_BO = language.Make("es_BO")
var tag_es_BR = language.Make("es_BR")
var tag_es_BZ = language.Make("es_BZ")
var tag_es_CL = language.Make("es_CL")
var tag_es_CO = language.Make("es_CO")
var tag_es_CR = language.Make("es_CR")
var tag_es_CU = language.Make("es_CU")
var tag_es_DO = language.Make("es_DO")
var tag_es_EA = language.Make("es_EA")
var tag_es_EC = language.Make("es_EC")
var tag_es_ES = language.Make("es_ES")
var tag_es_GQ = language.Make("es_GQ")
var tag_es_GT = language.Make("es_GT")
var tag_es_HN = language.Make("es_HN")
var tag_es_IC = language.Make("es_IC")
var tag_es_MX = language.Make("es_MX")
var tag_es_NI = language.Make("es_NI")
var tag_es_PA = language.Make("es_PA")
var tag_es_PE = language.Make("es_PE")
var tag_es_PH = language.Make("es_PH")
var tag_es_PR = language.Make("es_PR")
var tag_es_PY = language.Make("es_PY")
var tag_es_SV = language.Make("es_SV")
var tag_es_US = language.Make("es_US")
var tag_es_UY = language.Make("es_UY")
var tag_es_VE = language.Make("es_VE")
var tag_et = language.Make("et")
var tag_et_EE = language.Make("et_EE")
var tag_eu = language.Make("eu")
var tag_eu_ES = language.Make("eu_ES")
var tag_ewo = language.Make("ewo")
var tag_ewo_CM = language.Make("ewo_CM")
var tag_fa = language.Make("fa")
var tag_fa_AF = language.Make("fa_AF")
var tag_fa_IR = language.Make("fa_IR")
var tag_ff = language.Make("ff")
var tag_ff_Adlm = language.Make("ff_Adlm")
var tag_ff_Adlm_BF = language.Make("ff_Adlm_BF")
var tag_ff_Adlm_CM = language.Make("ff_Adlm_CM")
var tag_ff_Adlm_GH = language.Make("ff_Adlm_GH")
var tag_ff_Adlm_GM = language.Make("ff_Adlm_GM")
var tag_ff_Adlm_GN = language.Make("ff_Adlm_GN")
var tag_ff_Adlm_GW = language.Make("ff_Adlm_GW")
var tag_ff_Adlm_LR = language.Make("ff_Adlm_LR")
var tag_ff_Adlm_MR = language.Make("ff_Adlm_MR")
var tag_ff_Adlm_NE = language.Make("ff_Adlm_NE")
var tag_ff_Adlm_NG = language.Make("ff_Adlm_NG")
var tag_ff_Adlm_SL = language.Make("ff_Adlm_SL")
var tag_ff_Adlm_SN = language.Make("ff_Adlm_SN")
var tag_ff_Latn = language.Make("ff_Latn")
var tag_ff_Latn_BF = language.Make("ff_Latn_BF")
var tag_ff_Latn_CM = language.Make("ff_Latn_CM")
var tag_ff_Latn_GH = language.Make("ff_Latn_GH")
var tag_ff_Latn_GM = language.Make("ff_Latn_GM")
var tag_ff_Latn_GN = language.Make("ff_Latn_GN")
var tag_ff_Latn_GW = language.Make("ff_Latn_GW")
var tag_ff_Latn_LR = language.Make("ff_Latn_LR")
var tag_ff_Latn_MR = language.Make("ff_Latn_MR")
var tag_ff_Latn_NE = language.Make("ff_Latn_NE")
var tag_ff_Latn_NG = language.Make("ff_Latn_NG")
var tag_ff_Latn_SL = language.Make("ff_Latn_SL")
var tag_ff_Latn_SN = language.Make("ff_Latn_SN")
var tag_fi = language.Make("fi")
var tag_fi_FI = language.Make("fi_FI")
var tag_fil = language.Make("fil")
var tag_fil_PH = language.Make("fil_PH")
var tag_fo = language.Make("fo")
var tag_fo_DK = language.Make("fo_DK")
var tag_fo_FO = language.Make("fo_FO")
var tag_fr = language.Make("fr")
var tag_fr_BE = language.Make("fr_BE")
var tag_fr_BF = language.Make("fr_BF")
var tag_fr_BI = language.Make("fr_BI")
var tag_fr_BJ = language.Make("fr_BJ")
var tag_fr_BL = language.Make("fr_BL")
var tag_fr_CA = language.Make("fr_CA")
var tag_fr_CD = language.Make("fr_CD")
var tag_fr_CF = language.Make("fr_CF")
var tag_fr_CG = language.Make("fr_CG")
var tag_fr_CH = language.Make("fr_CH")
var tag_fr_CI = language.Make("fr_CI")
var tag_fr_CM = language.Make("fr_CM")
var tag_fr_DJ = language.Make("fr_DJ")
var tag_fr_DZ = language.Make("fr_DZ")
var tag_fr_FR = language.Make("fr_FR")
var tag_fr_GA = language.Make("fr_GA")
var tag_fr_GF = language.Make("fr_GF")
var tag_fr_GN = language.Make("fr_GN")
var tag_fr_GP = language.Make("fr_GP")
var tag_fr_GQ = language.Make("fr_GQ")
var tag_fr_HT = language.Make("fr_HT")
var tag_fr_KM = language.Make("fr_KM")
var tag_fr_LU = language.Make("fr_LU")
var tag_fr_MA = language.Make("fr_MA")
var tag_fr_MC = language.Make("fr_MC")
var tag_fr_MF = language.Make("fr_MF")
var tag_fr_MG = language.Make("fr_MG")
var tag_fr_ML = language.Make("fr_ML")
var tag_fr_MQ = language.Make("fr_MQ")
var tag_fr_MR = language.Make("fr_MR")
var tag_fr_MU = language.Make("fr_MU")
var tag_fr_NC = language.Make("fr_NC")
var tag_fr_NE = language.Make("fr_NE")
var tag_fr_PF = language.Make("fr_PF")
var tag_fr_PM = language.Make("fr_PM")
var tag_fr_RE = language.Make("fr_RE")
var tag_fr_RW = language.Make("fr_RW")
var tag_fr_SC = language.Make("fr_SC")
var tag_fr_SN = language.Make("fr_SN")
var tag_fr_SY = language.Make("fr_SY")
var tag_fr_TD = language.Make("fr_TD")
var tag_fr_TG = language.Make("fr_TG")
var tag_fr_TN = language.Make("fr_TN")
var tag_fr_VU = language.Make("fr_VU")
var tag_fr_WF = language.Make("fr_WF")
var tag_fr_YT = language.Make("fr_YT")
var tag_fur = language.Make("fur")
var tag_fur_IT = language.Make("fur_IT")
var tag_fy = language.Make("fy")
var tag_fy_NL = language.Make("fy_NL")
var tag_ga = language.Make("ga")
var tag_ga_GB = language.Make("ga_GB")
var tag_ga_IE = language.Make("ga_IE")
var tag_gd = language.Make("gd")
var tag_gd_GB = language.Make("gd_GB")
var tag_gl = language.Make("gl")
var tag_gl_ES = language.Make("gl_ES")
var tag_gsw = language.Make("gsw")
var tag_gsw_CH = language.Make("gsw_CH")
var tag_gsw_FR = language.Make("gsw_FR")
var tag_gsw_LI = language.Make("gsw_LI")
var tag_gu = language.Make("gu")
var tag_gu_IN = language.Make("gu_IN")
var tag_guw = language.Make("guw")
var tag_guz = language.Make("guz")
var tag_guz_KE = language.Make("guz_KE")
var tag_gv = language.Make("gv")
var tag_gv_IM = language.Make("gv_IM")
var tag_ha = language.Make("ha")
var tag_ha_GH = language.Make("ha_GH")
var tag_ha_NE = language.Make("ha_NE")
var tag_ha_NG = language.Make("ha_NG")
var tag_haw = language.Make("haw")
var tag_haw_US = language.Make("haw_US")
var tag_he = language.Make("he")
var tag_he_IL = language.Make("he_IL")
var tag_hi = language.Make("hi")
var tag_hi_IN = language.Make("hi_IN")
var tag_hr = language.Make("hr")
var tag_hr_BA = language.Make("hr_BA")
var tag_hr_HR = language.Make("hr_HR")
var tag_hsb = language.Make("hsb")
var tag_hsb_DE = language.Make("hsb_DE")
var tag_hu = language.Make("hu")
var tag_hu_HU = language.Make("hu_HU")
var tag_hy = language.Make("hy")
var tag_hy_AM = language.Make("hy_AM")
var tag_ia = language.Make("ia")
var tag_ia_001 = language.Make("ia_001")
var tag_id = language.Make("id")
var tag_id_ID = language.Make("id_ID")
var tag_ig = language.Make("ig")
var tag_ig_NG = language.Make("ig_NG")
var tag_ii = language.Make("ii")
var tag_ii_CN = language.Make("ii_CN")
var tag_in = language.Make("in")
var tag_io = language.Make("io")
var tag_is = language.Make("is")
var tag_is_IS = language.Make("is_IS")
var tag_it = language.Make("it")
var tag_it_CH = language.Make("it_CH")
var tag_it_IT = language.Make("it_IT")
var tag_it_SM = language.Make("it_SM")
var tag_it_VA = language.Make("it_VA")
var tag_iu = language.Make("iu")
var tag_iw = language.Make("iw")
var tag_ja = language.Make("ja")
var tag_ja_JP = language.Make("ja_JP")
var tag_jbo = language.Make("jbo")
var tag_jgo = language.Make("jgo")
var tag_jgo_CM = language.Make("jgo_CM")
var tag_ji = language.Make("ji")
var tag_jmc = language.Make("jmc")
var tag_jmc_TZ = language.Make("jmc_TZ")
var tag_jv = language.Make("jv")
var tag_jv_ID = language.Make("jv_ID")
var tag_jw = language.Make("jw")
var tag_ka = language.Make("ka")
var tag_ka_GE = language.Make("ka_GE")
var tag_kab = language.Make("kab")
var tag_kab_DZ = language.Make("kab_DZ")
var tag_kaj = language.Make("kaj")
var tag_kam = language.Make("kam")
var tag_kam_KE = language.Make("kam_KE")
var tag_kcg = language.Make("kcg")
var tag_kde = language.Make("kde")
var tag_kde_TZ = language.Make("kde_TZ")
var tag_kea = language.Make("kea")
var tag_kea_CV = language.Make("kea_CV")
var tag_khq = language.Make("khq")
var tag_khq_ML = language.Make("khq_ML")
var tag_ki = language.Make("ki")
var tag_ki_KE = language.Make("ki_KE")
var tag_kk = language.Make("kk")
var tag_kk_KZ = language.Make("kk_KZ")
var tag_kkj = language.Make("kkj")
var tag_kkj_CM = language.Make("kkj_CM")
var tag_kl = language.Make("kl")
var tag_kl_GL = language.Make("kl_GL")
var tag_kln = language.Make("kln")
var tag_kln_KE = language.Make("kln_KE")
var tag_km = language.Make("km")
var tag_km_KH = language.Make("km_KH")
var tag_kn = language.Make("kn")
var tag_kn_IN = language.Make("kn_IN")
var tag_ko = language.Make("ko")
var tag_ko_KP = language.Make("ko_KP")
var tag_ko_KR = language.Make("ko_KR")
var tag_kok = language.Make("kok")
var tag_kok_IN = language.Make("kok_IN")
var tag_ks = language.Make("ks")
var tag_ks_Arab = language.Make("ks_Arab")
var tag_ks_Arab_IN = language.Make("ks_Arab_IN")
var tag_ksb = language.Make("ksb")
var tag_ksb_TZ = language.Make("ksb_TZ")
var tag_ksf = language.Make("ksf")
var tag_ksf_CM = language.Make("ksf_CM")
var tag_ksh = language.Make("ksh")
var tag_ksh_DE = language.Make("ksh_DE")
var tag_ku = language.Make("ku")
var tag_ku_TR = language.Make("ku_TR")
var tag_kw = language.Make("kw")
var tag_kw_GB = language.Make("kw_GB")
var tag_ky = language.Make("ky")
var tag_ky_KG = language.Make("ky_KG")
var tag_lag = language.Make("lag")
var tag_lag_TZ = language.Make("lag_TZ")
var tag_lb = language.Make("lb")
var tag_lb_LU = language.Make("lb_LU")
var tag_lg = language.Make("lg")
var tag_lg_UG = language.Make("lg_UG")
var tag_lkt = language.Make("lkt")
var tag_lkt_US = language.Make("lkt_US")
var tag_ln = language.Make("ln")
var tag_ln_AO = language.Make("ln_AO")
var tag_ln_CD = language.Make("ln_CD")
var tag_ln_CF = language.Make("ln_CF")
var tag_ln_CG = language.Make("ln_CG")
var tag_lo = language.Make("lo")
var tag_lo_LA = language.Make("lo_LA")
var tag_lrc = language.Make("lrc")
var tag_lrc_IQ = language.Make("lrc_IQ")
var tag_lrc_IR = language.Make("lrc_IR")
var tag_lt = language.Make("lt")
var tag_lt_LT = language.Make("lt_LT")
var tag_lu = language.Make("lu")
var tag_lu_CD = language.Make("lu_CD")
var tag_luo = language.Make("luo")
var tag_luo_KE = language.Make("luo_KE")
var tag_luy = language.Make("luy")
var tag_luy_KE = language.Make("luy_KE")
var tag_lv = language.Make("lv")
var tag_lv_LV = language.Make("lv_LV")
var tag_mai = language.Make("mai")
var tag_mai_IN = language.Make("mai_IN")
var tag_mas = language.Make("mas")
var tag_mas_KE = language.Make("mas_KE")
var tag_mas_TZ = language.Make("mas_TZ")
var tag_mer = language.Make("mer")
var tag_mer_KE = language.Make("mer_KE")
var tag_mfe = language.Make("mfe")
var tag_mfe_MU = language.Make("mfe_MU")
var tag_mg = language.Make("mg")
var tag_mg_MG = language.Make("mg_MG")
var tag_mgh = language.Make("mgh")
var tag_mgh_MZ = language.Make("mgh_MZ")
var tag_mgo = language.Make("mgo")
var tag_mgo_CM = language.Make("mgo_CM")
var tag_mi = language.Make("mi")
var tag_mi_NZ = language.Make("mi_NZ")
var tag_mk = language.Make("mk")
var tag_mk_MK = language.Make("mk_MK")
var tag_ml = language.Make("ml")
var tag_ml_IN = language.Make("ml_IN")
var tag_mn = language.Make("mn")
var tag_mn_MN = language.Make("mn_MN")
var tag_mni = language.Make("mni")
var tag_mni_Beng = language.Make("mni_Beng")
var tag_mni_Beng_IN = language.Make("mni_Beng_IN")
var tag_mo = language.Make("mo")
var tag_mr = language.Make("mr")
var tag_mr_IN = language.Make("mr_IN")
var tag_ms = language.Make("ms")
var tag_ms_BN = language.Make("ms_BN")
var tag_ms_ID = language.Make("ms_ID")
var tag_ms_MY = language.Make("ms_MY")
var tag_ms_SG = language.Make("ms_SG")
var tag_mt = language.Make("mt")
var tag_mt_MT = language.Make("mt_MT")
var tag_mua = language.Make("mua")
var tag_mua_CM = language.Make("mua_CM")
var tag_my = language.Make("my")
var tag_my_MM = language.Make("my_MM")
var tag_mzn = language.Make("mzn")
var tag_mzn_IR = language.Make("mzn_IR")
var tag_nah = language.Make("nah")
var tag_naq = language.Make("naq")
var tag_naq_NA = language.Make("naq_NA")
var tag_nb = language.Make("nb")
var tag_nb_NO = language.Make("nb_NO")
var tag_nb_SJ = language.Make("nb_SJ")
var tag_nd = language.Make("nd")
var tag_nd_ZW = language.Make("nd_ZW")
var tag_nds = language.Make("nds")
var tag_nds_DE = language.Make("nds_DE")
var tag_nds_NL = language.Make("nds_NL")
var tag_ne = language.Make("ne")
var tag_ne_IN = language.Make("ne_IN")
var tag_ne_NP = language.Make("ne_NP")
var tag_nl = language.Make("nl")
var tag_nl_AW = language.Make("nl_AW")
var tag_nl_BE = language.Make("nl_BE")
var tag_nl_BQ = language.Make("nl_BQ")
var tag_nl_CW = language.Make("nl_CW")
var tag_nl_NL = language.Make("nl_NL")
var tag_nl_SR = language.Make("nl_SR")
var tag_nl_SX = language.Make("nl_SX")
var tag_nmg = language.Make("nmg")
var tag_nmg_CM = language.Make("nmg_CM")
var tag_nn = language.Make("nn")
var tag_nn_NO = language.Make("nn_NO")
var tag_nnh = language.Make("nnh")
var tag_nnh_CM = language.Make("nnh_CM")
var tag_no = language.Make("no")
var tag_nqo = language.Make("nqo")
var tag_nr = language.Make("nr")
var tag_nso = language.Make("nso")
var tag_nus = language.Make("nus")
var tag_nus_SS = language.Make("nus_SS")
var tag_ny = language.Make("ny")
var tag_nyn = language.Make("nyn")
var tag_nyn_UG = language.Make("nyn_UG")
var tag_om = language.Make("om")
var tag_om_ET = language.Make("om_ET")
var tag_om_KE = language.Make("om_KE")
var tag_or = language.Make("or")
var tag_or_IN = language.Make("or_IN")
var tag_os = language.Make("os")
var tag_os_GE = language.Make("os_GE")
var tag_os_RU = language.Make("os_RU")
var tag_osa = language.Make("osa")
var tag_pa = language.Make("pa")
var tag_pa_Arab = language.Make("pa_Arab")
var tag_pa_Arab_PK = language.Make("pa_Arab_PK")
var tag_pa_Guru = language.Make("pa_Guru")
var tag_pa_Guru_IN = language.Make("pa_Guru_IN")
var tag_pap = language.Make("pap")
var tag_pcm = language.Make("pcm")
var tag_pcm_NG = language.Make("pcm_NG")
var tag_pl = language.Make("pl")
var tag_pl_PL = language.Make("pl_PL")
var tag_prg = language.Make("prg")
var tag_prg_001 = language.Make("prg_001")
var tag_ps = language.Make("ps")
var tag_ps_AF = language.Make("ps_AF")
var tag_ps_PK = language.Make("ps_PK")
var tag_pt = language.Make("pt")
var tag_pt_AO = language.Make("pt_AO")
var tag_pt_BR = language.Make("pt_BR")
var tag_pt_CH = language.Make("pt_CH")
var tag_pt_CV = language.Make("pt_CV")
var tag_pt_GQ = language.Make("pt_GQ")
var tag_pt_GW = language.Make("pt_GW")
var tag_pt_LU = language.Make("pt_LU")
var tag_pt_MO = language.Make("pt_MO")
var tag_pt_MZ = language.Make("pt_MZ")
var tag_pt_PT = language.Make("pt_PT")
var tag_pt_ST = language.Make("pt_ST")
var tag_pt_TL = language.Make("pt_TL")
var tag_qu = language.Make("qu")
var tag_qu_BO = language.Make("qu_BO")
var tag_qu_EC = language.Make("qu_EC")
var tag_qu_PE = language.Make("qu_PE")
var tag_rm = language.Make("rm")
var tag_rm_CH = language.Make("rm_CH")
var tag_rn = language.Make("rn")
var tag_rn_BI = language.Make("rn_BI")
var tag_ro = language.Make("ro")
var tag_ro_MD = language.Make("ro_MD")
var tag_ro_RO = language.Make("ro_RO")
var tag_rof = language.Make("rof")
var tag_rof_TZ = language.Make("rof_TZ")
var tag_root = language.Make("root")
var tag_ru = language.Make("ru")
var tag_ru_BY = language.Make("ru_BY")
var tag_ru_KG = language.Make("ru_KG")
var tag_ru_KZ = language.Make("ru_KZ")
var tag_ru_MD = language.Make("ru_MD")
var tag_ru_RU = language.Make("ru_RU")
var tag_ru_UA = language.Make("ru_UA")
var tag_rw = language.Make("rw")
var tag_rw_RW = language.Make("rw_RW")
var tag_rwk = language.Make("rwk")
var tag_rwk_TZ = language.Make("rwk_TZ")
var tag_sah = language.Make("sah")
var tag_sah_RU = language.Make("sah_RU")
var tag_saq = language.Make("saq")
var tag_saq_KE = language.Make("saq_KE")
var tag_sat = language.Make("sat")
var tag_sat_Olck = language.Make("sat_Olck")
var tag_sat_Olck_IN = language.Make("sat_Olck_IN")
var tag_sbp = language.Make("sbp")
var tag_sbp_TZ = language.Make("sbp_TZ")
var tag_sc = language.Make("sc")
var tag_scn = language.Make("scn")
var tag_sd = language.Make("sd")
var tag_sd_Arab = language.Make("sd_Arab")
var tag_sd_Arab_PK = language.Make("sd_Arab_PK")
var tag_sd_Deva = language.Make("sd_Deva")
var tag_sd_Deva_IN = language.Make("sd_Deva_IN")
var tag_sdh = language.Make("sdh")
var tag_se = language.Make("se")
var tag_se_FI = language.Make("se_FI")
var tag_se_NO = language.Make("se_NO")
var tag_se_SE = language.Make("se_SE")
var tag_seh = language.Make("seh")
var tag_seh_MZ = language.Make("seh_MZ")
var tag_ses = language.Make("ses")
var tag_ses_ML = language.Make("ses_ML")
var tag_sg = language.Make("sg")
var tag_sg_CF = language.Make("sg_CF")
var tag_sh = language.Make("sh")
var tag_shi = language.Make("shi")
var tag_shi_Latn = language.Make("shi_Latn")
var tag_shi_Latn_MA = language.Make("shi_Latn_MA")
var tag_shi_Tfng = language.Make("shi_Tfng")
var tag_shi_Tfng_MA = language.Make("shi_Tfng_MA")
var tag_si = language.Make("si")
var tag_si_LK = language.Make("si_LK")
var tag_sk = language.Make("sk")
var tag_sk_SK = language.Make("sk_SK")
var tag_sl = language.Make("sl")
var tag_sl_SI = language.Make("sl_SI")
var tag_sma = language.Make("sma")
var tag_smi = language.Make("smi")
var tag_smj = language.Make("smj")
var tag_smn = language.Make("smn")
var tag_smn_FI = language.Make("smn_FI")
var tag_sms = language.Make("sms")
var tag_sn = language.Make("sn")
var tag_sn_ZW = language.Make("sn_ZW")
var tag_so = language.Make("so")
var tag_so_DJ = language.Make("so_DJ")
var tag_so_ET = language.Make("so_ET")
var tag_so_KE = language.Make("so_KE")
var tag_so_SO = language.Make("so_SO")
var tag_sq = language.Make("sq")
var tag_sq_AL = language.Make("sq_AL")
var tag_sq_MK = language.Make("sq_MK")
var tag_sq_XK = language.Make("sq_XK")
var tag_sr = language.Make("sr")
var tag_sr_Cyrl = language.Make("sr_Cyrl")
var tag_sr_Cyrl_BA = language.Make("sr_Cyrl_BA")
var tag_sr_Cyrl_ME = language.Make("sr_Cyrl_ME")
var tag_sr_Cyrl_RS = language.Make("sr_Cyrl_RS")
var tag_sr_Cyrl_XK = language.Make("sr_Cyrl_XK")
var tag_sr_Latn = language.Make("sr_Latn")
var tag_sr_Latn_BA = language.Make("sr_Latn_BA")
var tag_sr_Latn_ME = language.Make("sr_Latn_ME")
var tag_sr_Latn_RS = language.Make("sr_Latn_RS")
var tag_sr_Latn_XK = language.Make("sr_Latn_XK")
var tag_ss = language.Make("ss")
var tag_ssy = language.Make("ssy")
var tag_st = language.Make("st")
var tag_su = language.Make("su")
var tag_su_Latn = language.Make("su_Latn")
var tag_su_Latn_ID = language.Make("su_Latn_ID")
var tag_sv = language.Make("sv")
var tag_sv_AX = language.Make("sv_AX")
var tag_sv_FI = language.Make("sv_FI")
var tag_sv_SE = language.Make("sv_SE")
var tag_sw = language.Make("sw")
var tag_sw_CD = language.Make("sw_CD")
var tag_sw_KE = language.Make("sw_KE")
var tag_sw_TZ = language.Make("sw_TZ")
var tag_sw_UG = language.Make("sw_UG")
var tag_syr = language.Make("syr")
var tag_ta = language.Make("ta")
var tag_ta_IN = language.Make("ta_IN")
var tag_ta_LK = language.Make("ta_LK")
var tag_ta_MY = language.Make("ta_MY")
var tag_ta_SG = language.Make("ta_SG")
var tag_te = language.Make("te")
var tag_te_IN = language.Make("te_IN")
var tag_teo = language.Make("teo")
var tag_teo_KE = language.Make("teo_KE")
var tag_teo_UG = language.Make("teo_UG")
var tag_tg = language.Make("tg")
var tag_tg_TJ = language.Make("tg_TJ")
var tag_th = language.Make("th")
var tag_th_TH = language.Make("th_TH")
var tag_ti = language.Make("ti")
var tag_ti_ER = language.Make("ti_ER")
var tag_ti_ET = language.Make("ti_ET")
var tag_tig = language.Make("tig")
var tag_tk = language.Make("tk")
var tag_tk_TM = language.Make("tk_TM")
var tag_tl = language.Make("tl")
var tag_tn = language.Make("tn")
var tag_to = language.Make("to")
var tag_to_TO = language.Make("to_TO")
var tag_tr = language.Make("tr")
var tag_tr_CY = language.Make("tr_CY")
var tag_tr_TR = language.Make("tr_TR")
var tag_ts = language.Make("ts")
var tag_tt = language.Make("tt")
var tag_tt_RU = language.Make("tt_RU")
var tag_twq = language.Make("twq")
var tag_twq_NE = language.Make("twq_NE")
var tag_tzm = language.Make("tzm")
var tag_tzm_MA = language.Make("tzm_MA")
var tag_ug = language.Make("ug")
var tag_ug_CN = language.Make("ug_CN")
var tag_uk = language.Make("uk")
var tag_uk_UA = language.Make("uk_UA")
var tag_ur = language.Make("ur")
var tag_ur_IN = language.Make("ur_IN")
var tag_ur_PK = language.Make("ur_PK")
var tag_uz = language.Make("uz")
var tag_uz_Arab = language.Make("uz_Arab")
var tag_uz_Arab_AF = language.Make("uz_Arab_AF")
var tag_uz_Cyrl = language.Make("uz_Cyrl")
var tag_uz_Cyrl_UZ = language.Make("uz_Cyrl_UZ")
var tag_uz_Latn = language.Make("uz_Latn")
var tag_uz_Latn_UZ = language.Make("uz_Latn_UZ")
var tag_vai = language.Make("vai")
var tag_vai_Latn = language.Make("vai_Latn")
var tag_vai_Latn_LR = language.Make("vai_Latn_LR")
var tag_vai_Vaii = language.Make("vai_Vaii")
var tag_vai_Vaii_LR = language.Make("vai_Vaii_LR")
var tag_ve = language.Make("ve")
var tag_vi = language.Make("vi")
var tag_vi_VN = language.Make("vi_VN")
var tag_vo = language.Make("vo")
var tag_vo_001 = language.Make("vo_001")
var tag_vun = language.Make("vun")
var tag_vun_TZ = language.Make("vun_TZ")
var tag_wa = language.Make("wa")
var tag_wae = language.Make("wae")
var tag_wae_CH = language.Make("wae_CH")
var tag_wo = language.Make("wo")
var tag_wo_SN = language.Make("wo_SN")
var tag_xh = language.Make("xh")
var tag_xh_ZA = language.Make("xh_ZA")
var tag_xog = language.Make("xog")
var tag_xog_UG = language.Make("xog_UG")
var tag_yav = language.Make("yav")
var tag_yav_CM = language.Make("yav_CM")
var tag_yi = language.Make("yi")
var tag_yi_001 = language.Make("yi_001")
var tag_yo = language.Make("yo")
var tag_yo_BJ = language.Make("yo_BJ")
var tag_yo_NG = language.Make("yo_NG")
var tag_yue = language.Make("yue")
var tag_yue_Hans = language.Make("yue_Hans")
var tag_yue_Hans_CN = language.Make("yue_Hans_CN")
var tag_yue_Hant = language.Make("yue_Hant")
var tag_yue_Hant_HK = language.Make("yue_Hant_HK")
var tag_zgh = language.Make("zgh")
var tag_zgh_MA = language.Make("zgh_MA")
var tag_zh = language.Make("zh")
var tag_zh_Hans = language.Make("zh_Hans")
var tag_zh_Hans_CN = language.Make("zh_Hans_CN")
var tag_zh_Hans_HK = language.Make("zh_Hans_HK")
var tag_zh_Hans_MO = language.Make("zh_Hans_MO")
var tag_zh_Hans_SG = language.Make("zh_Hans_SG")
var tag_zh_Hant = language.Make("zh_Hant")
var tag_zh_Hant_HK = language.Make("zh_Hant_HK")
var tag_zh_Hant_MO = language.Make("zh_Hant_MO")
var tag_zh_Hant_TW = language.Make("zh_Hant_TW")
var tag_zu = language.Make("zu")
var tag_zu_ZA = language.Make("zu_ZA")
