//Code generated by make_resources.go; DO NOT EDIT
package locales

import (
	"golang.org/x/text/language"

	"github.com/razor-1/cldr"
)

type cldrData map[language.Tag]func() *cldr.Locale

var LocaleData = cldrData{
	tag_af:             getLocale_af,
	tag_af_NA:          getLocale_af_NA,
	tag_af_ZA:          getLocale_af_ZA,
	tag_agq:            getLocale_agq,
	tag_agq_CM:         getLocale_agq_CM,
	tag_ak:             getLocale_ak,
	tag_ak_GH:          getLocale_ak_GH,
	tag_am:             getLocale_am,
	tag_am_ET:          getLocale_am_ET,
	tag_ar:             getLocale_ar,
	tag_ar_001:         getLocale_ar_001,
	tag_ar_AE:          getLocale_ar_AE,
	tag_ar_BH:          getLocale_ar_BH,
	tag_ar_DJ:          getLocale_ar_DJ,
	tag_ar_DZ:          getLocale_ar_DZ,
	tag_ar_EG:          getLocale_ar_EG,
	tag_ar_EH:          getLocale_ar_EH,
	tag_ar_ER:          getLocale_ar_ER,
	tag_ar_IL:          getLocale_ar_IL,
	tag_ar_IQ:          getLocale_ar_IQ,
	tag_ar_JO:          getLocale_ar_JO,
	tag_ar_KM:          getLocale_ar_KM,
	tag_ar_KW:          getLocale_ar_KW,
	tag_ar_LB:          getLocale_ar_LB,
	tag_ar_LY:          getLocale_ar_LY,
	tag_ar_MA:          getLocale_ar_MA,
	tag_ar_MR:          getLocale_ar_MR,
	tag_ar_OM:          getLocale_ar_OM,
	tag_ar_PS:          getLocale_ar_PS,
	tag_ar_QA:          getLocale_ar_QA,
	tag_ar_SA:          getLocale_ar_SA,
	tag_ar_SD:          getLocale_ar_SD,
	tag_ar_SO:          getLocale_ar_SO,
	tag_ar_SS:          getLocale_ar_SS,
	tag_ar_SY:          getLocale_ar_SY,
	tag_ar_TD:          getLocale_ar_TD,
	tag_ar_TN:          getLocale_ar_TN,
	tag_ar_YE:          getLocale_ar_YE,
	tag_as:             getLocale_as,
	tag_as_IN:          getLocale_as_IN,
	tag_asa:            getLocale_asa,
	tag_asa_TZ:         getLocale_asa_TZ,
	tag_ast:            getLocale_ast,
	tag_ast_ES:         getLocale_ast_ES,
	tag_az:             getLocale_az,
	tag_az_Cyrl:        getLocale_az_Cyrl,
	tag_az_Cyrl_AZ:     getLocale_az_Cyrl_AZ,
	tag_az_Latn:        getLocale_az_Latn,
	tag_az_Latn_AZ:     getLocale_az_Latn_AZ,
	tag_bas:            getLocale_bas,
	tag_bas_CM:         getLocale_bas_CM,
	tag_be:             getLocale_be,
	tag_be_BY:          getLocale_be_BY,
	tag_bem:            getLocale_bem,
	tag_bem_ZM:         getLocale_bem_ZM,
	tag_bez:            getLocale_bez,
	tag_bez_TZ:         getLocale_bez_TZ,
	tag_bg:             getLocale_bg,
	tag_bg_BG:          getLocale_bg_BG,
	tag_bm:             getLocale_bm,
	tag_bm_ML:          getLocale_bm_ML,
	tag_bn:             getLocale_bn,
	tag_bn_BD:          getLocale_bn_BD,
	tag_bn_IN:          getLocale_bn_IN,
	tag_bo:             getLocale_bo,
	tag_bo_CN:          getLocale_bo_CN,
	tag_bo_IN:          getLocale_bo_IN,
	tag_br:             getLocale_br,
	tag_br_FR:          getLocale_br_FR,
	tag_brx:            getLocale_brx,
	tag_brx_IN:         getLocale_brx_IN,
	tag_bs:             getLocale_bs,
	tag_bs_Cyrl:        getLocale_bs_Cyrl,
	tag_bs_Cyrl_BA:     getLocale_bs_Cyrl_BA,
	tag_bs_Latn:        getLocale_bs_Latn,
	tag_bs_Latn_BA:     getLocale_bs_Latn_BA,
	tag_ca:             getLocale_ca,
	tag_ca_AD:          getLocale_ca_AD,
	tag_ca_ES:          getLocale_ca_ES,
	tag_ca_ES_VALENCIA: getLocale_ca_ES_VALENCIA,
	tag_ca_FR:          getLocale_ca_FR,
	tag_ca_IT:          getLocale_ca_IT,
	tag_ccp:            getLocale_ccp,
	tag_ccp_BD:         getLocale_ccp_BD,
	tag_ccp_IN:         getLocale_ccp_IN,
	tag_ce:             getLocale_ce,
	tag_ce_RU:          getLocale_ce_RU,
	tag_ceb:            getLocale_ceb,
	tag_ceb_PH:         getLocale_ceb_PH,
	tag_cgg:            getLocale_cgg,
	tag_cgg_UG:         getLocale_cgg_UG,
	tag_chr:            getLocale_chr,
	tag_chr_US:         getLocale_chr_US,
	tag_ckb:            getLocale_ckb,
	tag_ckb_IQ:         getLocale_ckb_IQ,
	tag_ckb_IR:         getLocale_ckb_IR,
	tag_cs:             getLocale_cs,
	tag_cs_CZ:          getLocale_cs_CZ,
	tag_cu:             getLocale_cu,
	tag_cu_RU:          getLocale_cu_RU,
	tag_cy:             getLocale_cy,
	tag_cy_GB:          getLocale_cy_GB,
	tag_da:             getLocale_da,
	tag_da_DK:          getLocale_da_DK,
	tag_da_GL:          getLocale_da_GL,
	tag_dav:            getLocale_dav,
	tag_dav_KE:         getLocale_dav_KE,
	tag_de:             getLocale_de,
	tag_de_AT:          getLocale_de_AT,
	tag_de_BE:          getLocale_de_BE,
	tag_de_CH:          getLocale_de_CH,
	tag_de_DE:          getLocale_de_DE,
	tag_de_IT:          getLocale_de_IT,
	tag_de_LI:          getLocale_de_LI,
	tag_de_LU:          getLocale_de_LU,
	tag_dje:            getLocale_dje,
	tag_dje_NE:         getLocale_dje_NE,
	tag_dsb:            getLocale_dsb,
	tag_dsb_DE:         getLocale_dsb_DE,
	tag_dua:            getLocale_dua,
	tag_dua_CM:         getLocale_dua_CM,
	tag_dyo:            getLocale_dyo,
	tag_dyo_SN:         getLocale_dyo_SN,
	tag_dz:             getLocale_dz,
	tag_dz_BT:          getLocale_dz_BT,
	tag_ebu:            getLocale_ebu,
	tag_ebu_KE:         getLocale_ebu_KE,
	tag_ee:             getLocale_ee,
	tag_ee_GH:          getLocale_ee_GH,
	tag_ee_TG:          getLocale_ee_TG,
	tag_el:             getLocale_el,
	tag_el_CY:          getLocale_el_CY,
	tag_el_GR:          getLocale_el_GR,
	tag_en:             getLocale_en,
	tag_en_001:         getLocale_en_001,
	tag_en_150:         getLocale_en_150,
	tag_en_AE:          getLocale_en_AE,
	tag_en_AG:          getLocale_en_AG,
	tag_en_AI:          getLocale_en_AI,
	tag_en_AS:          getLocale_en_AS,
	tag_en_AT:          getLocale_en_AT,
	tag_en_AU:          getLocale_en_AU,
	tag_en_BB:          getLocale_en_BB,
	tag_en_BE:          getLocale_en_BE,
	tag_en_BI:          getLocale_en_BI,
	tag_en_BM:          getLocale_en_BM,
	tag_en_BS:          getLocale_en_BS,
	tag_en_BW:          getLocale_en_BW,
	tag_en_BZ:          getLocale_en_BZ,
	tag_en_CA:          getLocale_en_CA,
	tag_en_CC:          getLocale_en_CC,
	tag_en_CH:          getLocale_en_CH,
	tag_en_CK:          getLocale_en_CK,
	tag_en_CM:          getLocale_en_CM,
	tag_en_CX:          getLocale_en_CX,
	tag_en_CY:          getLocale_en_CY,
	tag_en_DE:          getLocale_en_DE,
	tag_en_DG:          getLocale_en_DG,
	tag_en_DK:          getLocale_en_DK,
	tag_en_DM:          getLocale_en_DM,
	tag_en_ER:          getLocale_en_ER,
	tag_en_FI:          getLocale_en_FI,
	tag_en_FJ:          getLocale_en_FJ,
	tag_en_FK:          getLocale_en_FK,
	tag_en_FM:          getLocale_en_FM,
	tag_en_GB:          getLocale_en_GB,
	tag_en_GD:          getLocale_en_GD,
	tag_en_GG:          getLocale_en_GG,
	tag_en_GH:          getLocale_en_GH,
	tag_en_GI:          getLocale_en_GI,
	tag_en_GM:          getLocale_en_GM,
	tag_en_GU:          getLocale_en_GU,
	tag_en_GY:          getLocale_en_GY,
	tag_en_HK:          getLocale_en_HK,
	tag_en_IE:          getLocale_en_IE,
	tag_en_IL:          getLocale_en_IL,
	tag_en_IM:          getLocale_en_IM,
	tag_en_IN:          getLocale_en_IN,
	tag_en_IO:          getLocale_en_IO,
	tag_en_JE:          getLocale_en_JE,
	tag_en_JM:          getLocale_en_JM,
	tag_en_KE:          getLocale_en_KE,
	tag_en_KI:          getLocale_en_KI,
	tag_en_KN:          getLocale_en_KN,
	tag_en_KY:          getLocale_en_KY,
	tag_en_LC:          getLocale_en_LC,
	tag_en_LR:          getLocale_en_LR,
	tag_en_LS:          getLocale_en_LS,
	tag_en_MG:          getLocale_en_MG,
	tag_en_MH:          getLocale_en_MH,
	tag_en_MO:          getLocale_en_MO,
	tag_en_MP:          getLocale_en_MP,
	tag_en_MS:          getLocale_en_MS,
	tag_en_MT:          getLocale_en_MT,
	tag_en_MU:          getLocale_en_MU,
	tag_en_MW:          getLocale_en_MW,
	tag_en_MY:          getLocale_en_MY,
	tag_en_NA:          getLocale_en_NA,
	tag_en_NF:          getLocale_en_NF,
	tag_en_NG:          getLocale_en_NG,
	tag_en_NL:          getLocale_en_NL,
	tag_en_NR:          getLocale_en_NR,
	tag_en_NU:          getLocale_en_NU,
	tag_en_NZ:          getLocale_en_NZ,
	tag_en_PG:          getLocale_en_PG,
	tag_en_PH:          getLocale_en_PH,
	tag_en_PK:          getLocale_en_PK,
	tag_en_PN:          getLocale_en_PN,
	tag_en_PR:          getLocale_en_PR,
	tag_en_PW:          getLocale_en_PW,
	tag_en_RW:          getLocale_en_RW,
	tag_en_SB:          getLocale_en_SB,
	tag_en_SC:          getLocale_en_SC,
	tag_en_SD:          getLocale_en_SD,
	tag_en_SE:          getLocale_en_SE,
	tag_en_SG:          getLocale_en_SG,
	tag_en_SH:          getLocale_en_SH,
	tag_en_SI:          getLocale_en_SI,
	tag_en_SL:          getLocale_en_SL,
	tag_en_SS:          getLocale_en_SS,
	tag_en_SX:          getLocale_en_SX,
	tag_en_SZ:          getLocale_en_SZ,
	tag_en_TC:          getLocale_en_TC,
	tag_en_TK:          getLocale_en_TK,
	tag_en_TO:          getLocale_en_TO,
	tag_en_TT:          getLocale_en_TT,
	tag_en_TV:          getLocale_en_TV,
	tag_en_TZ:          getLocale_en_TZ,
	tag_en_UG:          getLocale_en_UG,
	tag_en_UM:          getLocale_en_UM,
	tag_en_US:          getLocale_en_US,
	tag_en_US_POSIX:    getLocale_en_US_POSIX,
	tag_en_VC:          getLocale_en_VC,
	tag_en_VG:          getLocale_en_VG,
	tag_en_VI:          getLocale_en_VI,
	tag_en_VU:          getLocale_en_VU,
	tag_en_WS:          getLocale_en_WS,
	tag_en_ZA:          getLocale_en_ZA,
	tag_en_ZM:          getLocale_en_ZM,
	tag_en_ZW:          getLocale_en_ZW,
	tag_eo:             getLocale_eo,
	tag_eo_001:         getLocale_eo_001,
	tag_es:             getLocale_es,
	tag_es_419:         getLocale_es_419,
	tag_es_AR:          getLocale_es_AR,
	tag_es_BO:          getLocale_es_BO,
	tag_es_BR:          getLocale_es_BR,
	tag_es_BZ:          getLocale_es_BZ,
	tag_es_CL:          getLocale_es_CL,
	tag_es_CO:          getLocale_es_CO,
	tag_es_CR:          getLocale_es_CR,
	tag_es_CU:          getLocale_es_CU,
	tag_es_DO:          getLocale_es_DO,
	tag_es_EA:          getLocale_es_EA,
	tag_es_EC:          getLocale_es_EC,
	tag_es_ES:          getLocale_es_ES,
	tag_es_GQ:          getLocale_es_GQ,
	tag_es_GT:          getLocale_es_GT,
	tag_es_HN:          getLocale_es_HN,
	tag_es_IC:          getLocale_es_IC,
	tag_es_MX:          getLocale_es_MX,
	tag_es_NI:          getLocale_es_NI,
	tag_es_PA:          getLocale_es_PA,
	tag_es_PE:          getLocale_es_PE,
	tag_es_PH:          getLocale_es_PH,
	tag_es_PR:          getLocale_es_PR,
	tag_es_PY:          getLocale_es_PY,
	tag_es_SV:          getLocale_es_SV,
	tag_es_US:          getLocale_es_US,
	tag_es_UY:          getLocale_es_UY,
	tag_es_VE:          getLocale_es_VE,
	tag_et:             getLocale_et,
	tag_et_EE:          getLocale_et_EE,
	tag_eu:             getLocale_eu,
	tag_eu_ES:          getLocale_eu_ES,
	tag_ewo:            getLocale_ewo,
	tag_ewo_CM:         getLocale_ewo_CM,
	tag_fa:             getLocale_fa,
	tag_fa_AF:          getLocale_fa_AF,
	tag_fa_IR:          getLocale_fa_IR,
	tag_ff:             getLocale_ff,
	tag_ff_Adlm:        getLocale_ff_Adlm,
	tag_ff_Adlm_BF:     getLocale_ff_Adlm_BF,
	tag_ff_Adlm_CM:     getLocale_ff_Adlm_CM,
	tag_ff_Adlm_GH:     getLocale_ff_Adlm_GH,
	tag_ff_Adlm_GM:     getLocale_ff_Adlm_GM,
	tag_ff_Adlm_GN:     getLocale_ff_Adlm_GN,
	tag_ff_Adlm_GW:     getLocale_ff_Adlm_GW,
	tag_ff_Adlm_LR:     getLocale_ff_Adlm_LR,
	tag_ff_Adlm_MR:     getLocale_ff_Adlm_MR,
	tag_ff_Adlm_NE:     getLocale_ff_Adlm_NE,
	tag_ff_Adlm_NG:     getLocale_ff_Adlm_NG,
	tag_ff_Adlm_SL:     getLocale_ff_Adlm_SL,
	tag_ff_Adlm_SN:     getLocale_ff_Adlm_SN,
	tag_ff_Latn:        getLocale_ff_Latn,
	tag_ff_Latn_BF:     getLocale_ff_Latn_BF,
	tag_ff_Latn_CM:     getLocale_ff_Latn_CM,
	tag_ff_Latn_GH:     getLocale_ff_Latn_GH,
	tag_ff_Latn_GM:     getLocale_ff_Latn_GM,
	tag_ff_Latn_GN:     getLocale_ff_Latn_GN,
	tag_ff_Latn_GW:     getLocale_ff_Latn_GW,
	tag_ff_Latn_LR:     getLocale_ff_Latn_LR,
	tag_ff_Latn_MR:     getLocale_ff_Latn_MR,
	tag_ff_Latn_NE:     getLocale_ff_Latn_NE,
	tag_ff_Latn_NG:     getLocale_ff_Latn_NG,
	tag_ff_Latn_SL:     getLocale_ff_Latn_SL,
	tag_ff_Latn_SN:     getLocale_ff_Latn_SN,
	tag_fi:             getLocale_fi,
	tag_fi_FI:          getLocale_fi_FI,
	tag_fil:            getLocale_fil,
	tag_fil_PH:         getLocale_fil_PH,
	tag_fo:             getLocale_fo,
	tag_fo_DK:          getLocale_fo_DK,
	tag_fo_FO:          getLocale_fo_FO,
	tag_fr:             getLocale_fr,
	tag_fr_BE:          getLocale_fr_BE,
	tag_fr_BF:          getLocale_fr_BF,
	tag_fr_BI:          getLocale_fr_BI,
	tag_fr_BJ:          getLocale_fr_BJ,
	tag_fr_BL:          getLocale_fr_BL,
	tag_fr_CA:          getLocale_fr_CA,
	tag_fr_CD:          getLocale_fr_CD,
	tag_fr_CF:          getLocale_fr_CF,
	tag_fr_CG:          getLocale_fr_CG,
	tag_fr_CH:          getLocale_fr_CH,
	tag_fr_CI:          getLocale_fr_CI,
	tag_fr_CM:          getLocale_fr_CM,
	tag_fr_DJ:          getLocale_fr_DJ,
	tag_fr_DZ:          getLocale_fr_DZ,
	tag_fr_FR:          getLocale_fr_FR,
	tag_fr_GA:          getLocale_fr_GA,
	tag_fr_GF:          getLocale_fr_GF,
	tag_fr_GN:          getLocale_fr_GN,
	tag_fr_GP:          getLocale_fr_GP,
	tag_fr_GQ:          getLocale_fr_GQ,
	tag_fr_HT:          getLocale_fr_HT,
	tag_fr_KM:          getLocale_fr_KM,
	tag_fr_LU:          getLocale_fr_LU,
	tag_fr_MA:          getLocale_fr_MA,
	tag_fr_MC:          getLocale_fr_MC,
	tag_fr_MF:          getLocale_fr_MF,
	tag_fr_MG:          getLocale_fr_MG,
	tag_fr_ML:          getLocale_fr_ML,
	tag_fr_MQ:          getLocale_fr_MQ,
	tag_fr_MR:          getLocale_fr_MR,
	tag_fr_MU:          getLocale_fr_MU,
	tag_fr_NC:          getLocale_fr_NC,
	tag_fr_NE:          getLocale_fr_NE,
	tag_fr_PF:          getLocale_fr_PF,
	tag_fr_PM:          getLocale_fr_PM,
	tag_fr_RE:          getLocale_fr_RE,
	tag_fr_RW:          getLocale_fr_RW,
	tag_fr_SC:          getLocale_fr_SC,
	tag_fr_SN:          getLocale_fr_SN,
	tag_fr_SY:          getLocale_fr_SY,
	tag_fr_TD:          getLocale_fr_TD,
	tag_fr_TG:          getLocale_fr_TG,
	tag_fr_TN:          getLocale_fr_TN,
	tag_fr_VU:          getLocale_fr_VU,
	tag_fr_WF:          getLocale_fr_WF,
	tag_fr_YT:          getLocale_fr_YT,
	tag_fur:            getLocale_fur,
	tag_fur_IT:         getLocale_fur_IT,
	tag_fy:             getLocale_fy,
	tag_fy_NL:          getLocale_fy_NL,
	tag_ga:             getLocale_ga,
	tag_ga_GB:          getLocale_ga_GB,
	tag_ga_IE:          getLocale_ga_IE,
	tag_gd:             getLocale_gd,
	tag_gd_GB:          getLocale_gd_GB,
	tag_gl:             getLocale_gl,
	tag_gl_ES:          getLocale_gl_ES,
	tag_gsw:            getLocale_gsw,
	tag_gsw_CH:         getLocale_gsw_CH,
	tag_gsw_FR:         getLocale_gsw_FR,
	tag_gsw_LI:         getLocale_gsw_LI,
	tag_gu:             getLocale_gu,
	tag_gu_IN:          getLocale_gu_IN,
	tag_guz:            getLocale_guz,
	tag_guz_KE:         getLocale_guz_KE,
	tag_gv:             getLocale_gv,
	tag_gv_IM:          getLocale_gv_IM,
	tag_ha:             getLocale_ha,
	tag_ha_GH:          getLocale_ha_GH,
	tag_ha_NE:          getLocale_ha_NE,
	tag_ha_NG:          getLocale_ha_NG,
	tag_haw:            getLocale_haw,
	tag_haw_US:         getLocale_haw_US,
	tag_he:             getLocale_he,
	tag_he_IL:          getLocale_he_IL,
	tag_hi:             getLocale_hi,
	tag_hi_IN:          getLocale_hi_IN,
	tag_hr:             getLocale_hr,
	tag_hr_BA:          getLocale_hr_BA,
	tag_hr_HR:          getLocale_hr_HR,
	tag_hsb:            getLocale_hsb,
	tag_hsb_DE:         getLocale_hsb_DE,
	tag_hu:             getLocale_hu,
	tag_hu_HU:          getLocale_hu_HU,
	tag_hy:             getLocale_hy,
	tag_hy_AM:          getLocale_hy_AM,
	tag_ia:             getLocale_ia,
	tag_ia_001:         getLocale_ia_001,
	tag_id:             getLocale_id,
	tag_id_ID:          getLocale_id_ID,
	tag_ig:             getLocale_ig,
	tag_ig_NG:          getLocale_ig_NG,
	tag_ii:             getLocale_ii,
	tag_ii_CN:          getLocale_ii_CN,
	tag_is:             getLocale_is,
	tag_is_IS:          getLocale_is_IS,
	tag_it:             getLocale_it,
	tag_it_CH:          getLocale_it_CH,
	tag_it_IT:          getLocale_it_IT,
	tag_it_SM:          getLocale_it_SM,
	tag_it_VA:          getLocale_it_VA,
	tag_ja:             getLocale_ja,
	tag_ja_JP:          getLocale_ja_JP,
	tag_jgo:            getLocale_jgo,
	tag_jgo_CM:         getLocale_jgo_CM,
	tag_jmc:            getLocale_jmc,
	tag_jmc_TZ:         getLocale_jmc_TZ,
	tag_jv:             getLocale_jv,
	tag_jv_ID:          getLocale_jv_ID,
	tag_ka:             getLocale_ka,
	tag_ka_GE:          getLocale_ka_GE,
	tag_kab:            getLocale_kab,
	tag_kab_DZ:         getLocale_kab_DZ,
	tag_kam:            getLocale_kam,
	tag_kam_KE:         getLocale_kam_KE,
	tag_kde:            getLocale_kde,
	tag_kde_TZ:         getLocale_kde_TZ,
	tag_kea:            getLocale_kea,
	tag_kea_CV:         getLocale_kea_CV,
	tag_khq:            getLocale_khq,
	tag_khq_ML:         getLocale_khq_ML,
	tag_ki:             getLocale_ki,
	tag_ki_KE:          getLocale_ki_KE,
	tag_kk:             getLocale_kk,
	tag_kk_KZ:          getLocale_kk_KZ,
	tag_kkj:            getLocale_kkj,
	tag_kkj_CM:         getLocale_kkj_CM,
	tag_kl:             getLocale_kl,
	tag_kl_GL:          getLocale_kl_GL,
	tag_kln:            getLocale_kln,
	tag_kln_KE:         getLocale_kln_KE,
	tag_km:             getLocale_km,
	tag_km_KH:          getLocale_km_KH,
	tag_kn:             getLocale_kn,
	tag_kn_IN:          getLocale_kn_IN,
	tag_ko:             getLocale_ko,
	tag_ko_KP:          getLocale_ko_KP,
	tag_ko_KR:          getLocale_ko_KR,
	tag_kok:            getLocale_kok,
	tag_kok_IN:         getLocale_kok_IN,
	tag_ks:             getLocale_ks,
	tag_ks_Arab:        getLocale_ks_Arab,
	tag_ks_Arab_IN:     getLocale_ks_Arab_IN,
	tag_ksb:            getLocale_ksb,
	tag_ksb_TZ:         getLocale_ksb_TZ,
	tag_ksf:            getLocale_ksf,
	tag_ksf_CM:         getLocale_ksf_CM,
	tag_ksh:            getLocale_ksh,
	tag_ksh_DE:         getLocale_ksh_DE,
	tag_ku:             getLocale_ku,
	tag_ku_TR:          getLocale_ku_TR,
	tag_kw:             getLocale_kw,
	tag_kw_GB:          getLocale_kw_GB,
	tag_ky:             getLocale_ky,
	tag_ky_KG:          getLocale_ky_KG,
	tag_lag:            getLocale_lag,
	tag_lag_TZ:         getLocale_lag_TZ,
	tag_lb:             getLocale_lb,
	tag_lb_LU:          getLocale_lb_LU,
	tag_lg:             getLocale_lg,
	tag_lg_UG:          getLocale_lg_UG,
	tag_lkt:            getLocale_lkt,
	tag_lkt_US:         getLocale_lkt_US,
	tag_ln:             getLocale_ln,
	tag_ln_AO:          getLocale_ln_AO,
	tag_ln_CD:          getLocale_ln_CD,
	tag_ln_CF:          getLocale_ln_CF,
	tag_ln_CG:          getLocale_ln_CG,
	tag_lo:             getLocale_lo,
	tag_lo_LA:          getLocale_lo_LA,
	tag_lrc:            getLocale_lrc,
	tag_lrc_IQ:         getLocale_lrc_IQ,
	tag_lrc_IR:         getLocale_lrc_IR,
	tag_lt:             getLocale_lt,
	tag_lt_LT:          getLocale_lt_LT,
	tag_lu:             getLocale_lu,
	tag_lu_CD:          getLocale_lu_CD,
	tag_luo:            getLocale_luo,
	tag_luo_KE:         getLocale_luo_KE,
	tag_luy:            getLocale_luy,
	tag_luy_KE:         getLocale_luy_KE,
	tag_lv:             getLocale_lv,
	tag_lv_LV:          getLocale_lv_LV,
	tag_mai:            getLocale_mai,
	tag_mai_IN:         getLocale_mai_IN,
	tag_mas:            getLocale_mas,
	tag_mas_KE:         getLocale_mas_KE,
	tag_mas_TZ:         getLocale_mas_TZ,
	tag_mer:            getLocale_mer,
	tag_mer_KE:         getLocale_mer_KE,
	tag_mfe:            getLocale_mfe,
	tag_mfe_MU:         getLocale_mfe_MU,
	tag_mg:             getLocale_mg,
	tag_mg_MG:          getLocale_mg_MG,
	tag_mgh:            getLocale_mgh,
	tag_mgh_MZ:         getLocale_mgh_MZ,
	tag_mgo:            getLocale_mgo,
	tag_mgo_CM:         getLocale_mgo_CM,
	tag_mi:             getLocale_mi,
	tag_mi_NZ:          getLocale_mi_NZ,
	tag_mk:             getLocale_mk,
	tag_mk_MK:          getLocale_mk_MK,
	tag_ml:             getLocale_ml,
	tag_ml_IN:          getLocale_ml_IN,
	tag_mn:             getLocale_mn,
	tag_mn_MN:          getLocale_mn_MN,
	tag_mni:            getLocale_mni,
	tag_mni_Beng:       getLocale_mni_Beng,
	tag_mni_Beng_IN:    getLocale_mni_Beng_IN,
	tag_mr:             getLocale_mr,
	tag_mr_IN:          getLocale_mr_IN,
	tag_ms:             getLocale_ms,
	tag_ms_BN:          getLocale_ms_BN,
	tag_ms_ID:          getLocale_ms_ID,
	tag_ms_MY:          getLocale_ms_MY,
	tag_ms_SG:          getLocale_ms_SG,
	tag_mt:             getLocale_mt,
	tag_mt_MT:          getLocale_mt_MT,
	tag_mua:            getLocale_mua,
	tag_mua_CM:         getLocale_mua_CM,
	tag_my:             getLocale_my,
	tag_my_MM:          getLocale_my_MM,
	tag_mzn:            getLocale_mzn,
	tag_mzn_IR:         getLocale_mzn_IR,
	tag_naq:            getLocale_naq,
	tag_naq_NA:         getLocale_naq_NA,
	tag_nb:             getLocale_nb,
	tag_nb_NO:          getLocale_nb_NO,
	tag_nb_SJ:          getLocale_nb_SJ,
	tag_nd:             getLocale_nd,
	tag_nd_ZW:          getLocale_nd_ZW,
	tag_nds:            getLocale_nds,
	tag_nds_DE:         getLocale_nds_DE,
	tag_nds_NL:         getLocale_nds_NL,
	tag_ne:             getLocale_ne,
	tag_ne_IN:          getLocale_ne_IN,
	tag_ne_NP:          getLocale_ne_NP,
	tag_nl:             getLocale_nl,
	tag_nl_AW:          getLocale_nl_AW,
	tag_nl_BE:          getLocale_nl_BE,
	tag_nl_BQ:          getLocale_nl_BQ,
	tag_nl_CW:          getLocale_nl_CW,
	tag_nl_NL:          getLocale_nl_NL,
	tag_nl_SR:          getLocale_nl_SR,
	tag_nl_SX:          getLocale_nl_SX,
	tag_nmg:            getLocale_nmg,
	tag_nmg_CM:         getLocale_nmg_CM,
	tag_nn:             getLocale_nn,
	tag_nn_NO:          getLocale_nn_NO,
	tag_nnh:            getLocale_nnh,
	tag_nnh_CM:         getLocale_nnh_CM,
	tag_nus:            getLocale_nus,
	tag_nus_SS:         getLocale_nus_SS,
	tag_nyn:            getLocale_nyn,
	tag_nyn_UG:         getLocale_nyn_UG,
	tag_om:             getLocale_om,
	tag_om_ET:          getLocale_om_ET,
	tag_om_KE:          getLocale_om_KE,
	tag_or:             getLocale_or,
	tag_or_IN:          getLocale_or_IN,
	tag_os:             getLocale_os,
	tag_os_GE:          getLocale_os_GE,
	tag_os_RU:          getLocale_os_RU,
	tag_pa:             getLocale_pa,
	tag_pa_Arab:        getLocale_pa_Arab,
	tag_pa_Arab_PK:     getLocale_pa_Arab_PK,
	tag_pa_Guru:        getLocale_pa_Guru,
	tag_pa_Guru_IN:     getLocale_pa_Guru_IN,
	tag_pcm:            getLocale_pcm,
	tag_pcm_NG:         getLocale_pcm_NG,
	tag_pl:             getLocale_pl,
	tag_pl_PL:          getLocale_pl_PL,
	tag_prg:            getLocale_prg,
	tag_prg_001:        getLocale_prg_001,
	tag_ps:             getLocale_ps,
	tag_ps_AF:          getLocale_ps_AF,
	tag_ps_PK:          getLocale_ps_PK,
	tag_pt:             getLocale_pt,
	tag_pt_AO:          getLocale_pt_AO,
	tag_pt_BR:          getLocale_pt_BR,
	tag_pt_CH:          getLocale_pt_CH,
	tag_pt_CV:          getLocale_pt_CV,
	tag_pt_GQ:          getLocale_pt_GQ,
	tag_pt_GW:          getLocale_pt_GW,
	tag_pt_LU:          getLocale_pt_LU,
	tag_pt_MO:          getLocale_pt_MO,
	tag_pt_MZ:          getLocale_pt_MZ,
	tag_pt_PT:          getLocale_pt_PT,
	tag_pt_ST:          getLocale_pt_ST,
	tag_pt_TL:          getLocale_pt_TL,
	tag_qu:             getLocale_qu,
	tag_qu_BO:          getLocale_qu_BO,
	tag_qu_EC:          getLocale_qu_EC,
	tag_qu_PE:          getLocale_qu_PE,
	tag_rm:             getLocale_rm,
	tag_rm_CH:          getLocale_rm_CH,
	tag_rn:             getLocale_rn,
	tag_rn_BI:          getLocale_rn_BI,
	tag_ro:             getLocale_ro,
	tag_ro_MD:          getLocale_ro_MD,
	tag_ro_RO:          getLocale_ro_RO,
	tag_rof:            getLocale_rof,
	tag_rof_TZ:         getLocale_rof_TZ,
	tag_root:           getLocale_root,
	tag_ru:             getLocale_ru,
	tag_ru_BY:          getLocale_ru_BY,
	tag_ru_KG:          getLocale_ru_KG,
	tag_ru_KZ:          getLocale_ru_KZ,
	tag_ru_MD:          getLocale_ru_MD,
	tag_ru_RU:          getLocale_ru_RU,
	tag_ru_UA:          getLocale_ru_UA,
	tag_rw:             getLocale_rw,
	tag_rw_RW:          getLocale_rw_RW,
	tag_rwk:            getLocale_rwk,
	tag_rwk_TZ:         getLocale_rwk_TZ,
	tag_sah:            getLocale_sah,
	tag_sah_RU:         getLocale_sah_RU,
	tag_saq:            getLocale_saq,
	tag_saq_KE:         getLocale_saq_KE,
	tag_sat:            getLocale_sat,
	tag_sat_Olck:       getLocale_sat_Olck,
	tag_sat_Olck_IN:    getLocale_sat_Olck_IN,
	tag_sbp:            getLocale_sbp,
	tag_sbp_TZ:         getLocale_sbp_TZ,
	tag_sd:             getLocale_sd,
	tag_sd_Arab:        getLocale_sd_Arab,
	tag_sd_Arab_PK:     getLocale_sd_Arab_PK,
	tag_sd_Deva:        getLocale_sd_Deva,
	tag_sd_Deva_IN:     getLocale_sd_Deva_IN,
	tag_se:             getLocale_se,
	tag_se_FI:          getLocale_se_FI,
	tag_se_NO:          getLocale_se_NO,
	tag_se_SE:          getLocale_se_SE,
	tag_seh:            getLocale_seh,
	tag_seh_MZ:         getLocale_seh_MZ,
	tag_ses:            getLocale_ses,
	tag_ses_ML:         getLocale_ses_ML,
	tag_sg:             getLocale_sg,
	tag_sg_CF:          getLocale_sg_CF,
	tag_shi:            getLocale_shi,
	tag_shi_Latn:       getLocale_shi_Latn,
	tag_shi_Latn_MA:    getLocale_shi_Latn_MA,
	tag_shi_Tfng:       getLocale_shi_Tfng,
	tag_shi_Tfng_MA:    getLocale_shi_Tfng_MA,
	tag_si:             getLocale_si,
	tag_si_LK:          getLocale_si_LK,
	tag_sk:             getLocale_sk,
	tag_sk_SK:          getLocale_sk_SK,
	tag_sl:             getLocale_sl,
	tag_sl_SI:          getLocale_sl_SI,
	tag_smn:            getLocale_smn,
	tag_smn_FI:         getLocale_smn_FI,
	tag_sn:             getLocale_sn,
	tag_sn_ZW:          getLocale_sn_ZW,
	tag_so:             getLocale_so,
	tag_so_DJ:          getLocale_so_DJ,
	tag_so_ET:          getLocale_so_ET,
	tag_so_KE:          getLocale_so_KE,
	tag_so_SO:          getLocale_so_SO,
	tag_sq:             getLocale_sq,
	tag_sq_AL:          getLocale_sq_AL,
	tag_sq_MK:          getLocale_sq_MK,
	tag_sq_XK:          getLocale_sq_XK,
	tag_sr:             getLocale_sr,
	tag_sr_Cyrl:        getLocale_sr_Cyrl,
	tag_sr_Cyrl_BA:     getLocale_sr_Cyrl_BA,
	tag_sr_Cyrl_ME:     getLocale_sr_Cyrl_ME,
	tag_sr_Cyrl_RS:     getLocale_sr_Cyrl_RS,
	tag_sr_Cyrl_XK:     getLocale_sr_Cyrl_XK,
	tag_sr_Latn:        getLocale_sr_Latn,
	tag_sr_Latn_BA:     getLocale_sr_Latn_BA,
	tag_sr_Latn_ME:     getLocale_sr_Latn_ME,
	tag_sr_Latn_RS:     getLocale_sr_Latn_RS,
	tag_sr_Latn_XK:     getLocale_sr_Latn_XK,
	tag_su:             getLocale_su,
	tag_su_Latn:        getLocale_su_Latn,
	tag_su_Latn_ID:     getLocale_su_Latn_ID,
	tag_sv:             getLocale_sv,
	tag_sv_AX:          getLocale_sv_AX,
	tag_sv_FI:          getLocale_sv_FI,
	tag_sv_SE:          getLocale_sv_SE,
	tag_sw:             getLocale_sw,
	tag_sw_CD:          getLocale_sw_CD,
	tag_sw_KE:          getLocale_sw_KE,
	tag_sw_TZ:          getLocale_sw_TZ,
	tag_sw_UG:          getLocale_sw_UG,
	tag_ta:             getLocale_ta,
	tag_ta_IN:          getLocale_ta_IN,
	tag_ta_LK:          getLocale_ta_LK,
	tag_ta_MY:          getLocale_ta_MY,
	tag_ta_SG:          getLocale_ta_SG,
	tag_te:             getLocale_te,
	tag_te_IN:          getLocale_te_IN,
	tag_teo:            getLocale_teo,
	tag_teo_KE:         getLocale_teo_KE,
	tag_teo_UG:         getLocale_teo_UG,
	tag_tg:             getLocale_tg,
	tag_tg_TJ:          getLocale_tg_TJ,
	tag_th:             getLocale_th,
	tag_th_TH:          getLocale_th_TH,
	tag_ti:             getLocale_ti,
	tag_ti_ER:          getLocale_ti_ER,
	tag_ti_ET:          getLocale_ti_ET,
	tag_tk:             getLocale_tk,
	tag_tk_TM:          getLocale_tk_TM,
	tag_to:             getLocale_to,
	tag_to_TO:          getLocale_to_TO,
	tag_tr:             getLocale_tr,
	tag_tr_CY:          getLocale_tr_CY,
	tag_tr_TR:          getLocale_tr_TR,
	tag_tt:             getLocale_tt,
	tag_tt_RU:          getLocale_tt_RU,
	tag_twq:            getLocale_twq,
	tag_twq_NE:         getLocale_twq_NE,
	tag_tzm:            getLocale_tzm,
	tag_tzm_MA:         getLocale_tzm_MA,
	tag_ug:             getLocale_ug,
	tag_ug_CN:          getLocale_ug_CN,
	tag_uk:             getLocale_uk,
	tag_uk_UA:          getLocale_uk_UA,
	tag_ur:             getLocale_ur,
	tag_ur_IN:          getLocale_ur_IN,
	tag_ur_PK:          getLocale_ur_PK,
	tag_uz:             getLocale_uz,
	tag_uz_Arab:        getLocale_uz_Arab,
	tag_uz_Arab_AF:     getLocale_uz_Arab_AF,
	tag_uz_Cyrl:        getLocale_uz_Cyrl,
	tag_uz_Cyrl_UZ:     getLocale_uz_Cyrl_UZ,
	tag_uz_Latn:        getLocale_uz_Latn,
	tag_uz_Latn_UZ:     getLocale_uz_Latn_UZ,
	tag_vai:            getLocale_vai,
	tag_vai_Latn:       getLocale_vai_Latn,
	tag_vai_Latn_LR:    getLocale_vai_Latn_LR,
	tag_vai_Vaii:       getLocale_vai_Vaii,
	tag_vai_Vaii_LR:    getLocale_vai_Vaii_LR,
	tag_vi:             getLocale_vi,
	tag_vi_VN:          getLocale_vi_VN,
	tag_vo:             getLocale_vo,
	tag_vo_001:         getLocale_vo_001,
	tag_vun:            getLocale_vun,
	tag_vun_TZ:         getLocale_vun_TZ,
	tag_wae:            getLocale_wae,
	tag_wae_CH:         getLocale_wae_CH,
	tag_wo:             getLocale_wo,
	tag_wo_SN:          getLocale_wo_SN,
	tag_xh:             getLocale_xh,
	tag_xh_ZA:          getLocale_xh_ZA,
	tag_xog:            getLocale_xog,
	tag_xog_UG:         getLocale_xog_UG,
	tag_yav:            getLocale_yav,
	tag_yav_CM:         getLocale_yav_CM,
	tag_yi:             getLocale_yi,
	tag_yi_001:         getLocale_yi_001,
	tag_yo:             getLocale_yo,
	tag_yo_BJ:          getLocale_yo_BJ,
	tag_yo_NG:          getLocale_yo_NG,
	tag_yue:            getLocale_yue,
	tag_yue_Hans:       getLocale_yue_Hans,
	tag_yue_Hans_CN:    getLocale_yue_Hans_CN,
	tag_yue_Hant:       getLocale_yue_Hant,
	tag_yue_Hant_HK:    getLocale_yue_Hant_HK,
	tag_zgh:            getLocale_zgh,
	tag_zgh_MA:         getLocale_zgh_MA,
	tag_zh:             getLocale_zh,
	tag_zh_Hans:        getLocale_zh_Hans,
	tag_zh_Hans_CN:     getLocale_zh_Hans_CN,
	tag_zh_Hans_HK:     getLocale_zh_Hans_HK,
	tag_zh_Hans_MO:     getLocale_zh_Hans_MO,
	tag_zh_Hans_SG:     getLocale_zh_Hans_SG,
	tag_zh_Hant:        getLocale_zh_Hant,
	tag_zh_Hant_HK:     getLocale_zh_Hant_HK,
	tag_zh_Hant_MO:     getLocale_zh_Hant_MO,
	tag_zh_Hant_TW:     getLocale_zh_Hant_TW,
	tag_zu:             getLocale_zu,
	tag_zu_ZA:          getLocale_zu_ZA,
}

var tag_af = language.Make("af")
var tag_af_NA = language.Make("af_NA")
var tag_af_ZA = language.Make("af_ZA")
var tag_agq = language.Make("agq")
var tag_agq_CM = language.Make("agq_CM")
var tag_ak = language.Make("ak")
var tag_ak_GH = language.Make("ak_GH")
var tag_am = language.Make("am")
var tag_am_ET = language.Make("am_ET")
var tag_an = language.Make("an")
var tag_ar = language.Make("ar")
var tag_ar_001 = language.Make("ar_001")
var tag_ar_AE = language.Make("ar_AE")
var tag_ar_BH = language.Make("ar_BH")
var tag_ar_DJ = language.Make("ar_DJ")
var tag_ar_DZ = language.Make("ar_DZ")
var tag_ar_EG = language.Make("ar_EG")
var tag_ar_EH = language.Make("ar_EH")
var tag_ar_ER = language.Make("ar_ER")
var tag_ar_IL = language.Make("ar_IL")
var tag_ar_IQ = language.Make("ar_IQ")
var tag_ar_JO = language.Make("ar_JO")
var tag_ar_KM = language.Make("ar_KM")
var tag_ar_KW = language.Make("ar_KW")
var tag_ar_LB = language.Make("ar_LB")
var tag_ar_LY = language.Make("ar_LY")
var tag_ar_MA = language.Make("ar_MA")
var tag_ar_MR = language.Make("ar_MR")
var tag_ar_OM = language.Make("ar_OM")
var tag_ar_PS = language.Make("ar_PS")
var tag_ar_QA = language.Make("ar_QA")
var tag_ar_SA = language.Make("ar_SA")
var tag_ar_SD = language.Make("ar_SD")
var tag_ar_SO = language.Make("ar_SO")
var tag_ar_SS = language.Make("ar_SS")
var tag_ar_SY = language.Make("ar_SY")
var tag_ar_TD = language.Make("ar_TD")
var tag_ar_TN = language.Make("ar_TN")
var tag_ar_YE = language.Make("ar_YE")
var tag_ars = language.Make("ars")
var tag_as = language.Make("as")
var tag_as_IN = language.Make("as_IN")
var tag_asa = language.Make("asa")
var tag_asa_TZ = language.Make("asa_TZ")
var tag_ast = language.Make("ast")
var tag_ast_ES = language.Make("ast_ES")
var tag_az = language.Make("az")
var tag_az_Cyrl = language.Make("az_Cyrl")
var tag_az_Cyrl_AZ = language.Make("az_Cyrl_AZ")
var tag_az_Latn = language.Make("az_Latn")
var tag_az_Latn_AZ = language.Make("az_Latn_AZ")
var tag_bas = language.Make("bas")
var tag_bas_CM = language.Make("bas_CM")
var tag_be = language.Make("be")
var tag_be_BY = language.Make("be_BY")
var tag_bem = language.Make("bem")
var tag_bem_ZM = language.Make("bem_ZM")
var tag_bez = language.Make("bez")
var tag_bez_TZ = language.Make("bez_TZ")
var tag_bg = language.Make("bg")
var tag_bg_BG = language.Make("bg_BG")
var tag_bho = language.Make("bho")
var tag_bm = language.Make("bm")
var tag_bm_ML = language.Make("bm_ML")
var tag_bn = language.Make("bn")
var tag_bn_BD = language.Make("bn_BD")
var tag_bn_IN = language.Make("bn_IN")
var tag_bo = language.Make("bo")
var tag_bo_CN = language.Make("bo_CN")
var tag_bo_IN = language.Make("bo_IN")
var tag_br = language.Make("br")
var tag_br_FR = language.Make("br_FR")
var tag_brx = language.Make("brx")
var tag_brx_IN = language.Make("brx_IN")
var tag_bs = language.Make("bs")
var tag_bs_Cyrl = language.Make("bs_Cyrl")
var tag_bs_Cyrl_BA = language.Make("bs_Cyrl_BA")
var tag_bs_Latn = language.Make("bs_Latn")
var tag_bs_Latn_BA = language.Make("bs_Latn_BA")
var tag_ca = language.Make("ca")
var tag_ca_AD = language.Make("ca_AD")
var tag_ca_ES = language.Make("ca_ES")
var tag_ca_ES_VALENCIA = language.Make("ca_ES_VALENCIA")
var tag_ca_FR = language.Make("ca_FR")
var tag_ca_IT = language.Make("ca_IT")
var tag_ccp = language.Make("ccp")
var tag_ccp_BD = language.Make("ccp_BD")
var tag_ccp_IN = language.Make("ccp_IN")
var tag_ce = language.Make("ce")
var tag_ce_RU = language.Make("ce_RU")
var tag_ceb = language.Make("ceb")
var tag_ceb_PH = language.Make("ceb_PH")
var tag_cgg = language.Make("cgg")
var tag_cgg_UG = language.Make("cgg_UG")
var tag_chr = language.Make("chr")
var tag_chr_US = language.Make("chr_US")
var tag_ckb = language.Make("ckb")
var tag_ckb_IQ = language.Make("ckb_IQ")
var tag_ckb_IR = language.Make("ckb_IR")
var tag_cs = language.Make("cs")
var tag_cs_CZ = language.Make("cs_CZ")
var tag_cu = language.Make("cu")
var tag_cu_RU = language.Make("cu_RU")
var tag_cy = language.Make("cy")
var tag_cy_GB = language.Make("cy_GB")
var tag_da = language.Make("da")
var tag_da_DK = language.Make("da_DK")
var tag_da_GL = language.Make("da_GL")
var tag_dav = language.Make("dav")
var tag_dav_KE = language.Make("dav_KE")
var tag_de = language.Make("de")
var tag_de_AT = language.Make("de_AT")
var tag_de_BE = language.Make("de_BE")
var tag_de_CH = language.Make("de_CH")
var tag_de_DE = language.Make("de_DE")
var tag_de_IT = language.Make("de_IT")
var tag_de_LI = language.Make("de_LI")
var tag_de_LU = language.Make("de_LU")
var tag_dje = language.Make("dje")
var tag_dje_NE = language.Make("dje_NE")
var tag_dsb = language.Make("dsb")
var tag_dsb_DE = language.Make("dsb_DE")
var tag_dua = language.Make("dua")
var tag_dua_CM = language.Make("dua_CM")
var tag_dv = language.Make("dv")
var tag_dyo = language.Make("dyo")
var tag_dyo_SN = language.Make("dyo_SN")
var tag_dz = language.Make("dz")
var tag_dz_BT = language.Make("dz_BT")
var tag_ebu = language.Make("ebu")
var tag_ebu_KE = language.Make("ebu_KE")
var tag_ee = language.Make("ee")
var tag_ee_GH = language.Make("ee_GH")
var tag_ee_TG = language.Make("ee_TG")
var tag_el = language.Make("el")
var tag_el_CY = language.Make("el_CY")
var tag_el_GR = language.Make("el_GR")
var tag_en = language.Make("en")
var tag_en_001 = language.Make("en_001")
var tag_en_150 = language.Make("en_150")
var tag_en_AE = language.Make("en_AE")
var tag_en_AG = language.Make("en_AG")
var tag_en_AI = language.Make("en_AI")
var tag_en_AS = language.Make("en_AS")
var tag_en_AT = language.Make("en_AT")
var tag_en_AU = language.Make("en_AU")
var tag_en_BB = language.Make("en_BB")
var tag_en_BE = language.Make("en_BE")
var tag_en_BI = language.Make("en_BI")
var tag_en_BM = language.Make("en_BM")
var tag_en_BS = language.Make("en_BS")
var tag_en_BW = language.Make("en_BW")
var tag_en_BZ = language.Make("en_BZ")
var tag_en_CA = language.Make("en_CA")
var tag_en_CC = language.Make("en_CC")
var tag_en_CH = language.Make("en_CH")
var tag_en_CK = language.Make("en_CK")
var tag_en_CM = language.Make("en_CM")
var tag_en_CX = language.Make("en_CX")
var tag_en_CY = language.Make("en_CY")
var tag_en_DE = language.Make("en_DE")
var tag_en_DG = language.Make("en_DG")
var tag_en_DK = language.Make("en_DK")
var tag_en_DM = language.Make("en_DM")
var tag_en_ER = language.Make("en_ER")
var tag_en_FI = language.Make("en_FI")
var tag_en_FJ = language.Make("en_FJ")
var tag_en_FK = language.Make("en_FK")
var tag_en_FM = language.Make("en_FM")
var tag_en_GB = language.Make("en_GB")
var tag_en_GD = language.Make("en_GD")
var tag_en_GG = language.Make("en_GG")
var tag_en_GH = language.Make("en_GH")
var tag_en_GI = language.Make("en_GI")
var tag_en_GM = language.Make("en_GM")
var tag_en_GU = language.Make("en_GU")
var tag_en_GY = language.Make("en_GY")
var tag_en_HK = language.Make("en_HK")
var tag_en_IE = language.Make("en_IE")
var tag_en_IL = language.Make("en_IL")
var tag_en_IM = language.Make("en_IM")
var tag_en_IN = language.Make("en_IN")
var tag_en_IO = language.Make("en_IO")
var tag_en_JE = language.Make("en_JE")
var tag_en_JM = language.Make("en_JM")
var tag_en_KE = language.Make("en_KE")
var tag_en_KI = language.Make("en_KI")
var tag_en_KN = language.Make("en_KN")
var tag_en_KY = language.Make("en_KY")
var tag_en_LC = language.Make("en_LC")
var tag_en_LR = language.Make("en_LR")
var tag_en_LS = language.Make("en_LS")
var tag_en_MG = language.Make("en_MG")
var tag_en_MH = language.Make("en_MH")
var tag_en_MO = language.Make("en_MO")
var tag_en_MP = language.Make("en_MP")
var tag_en_MS = language.Make("en_MS")
var tag_en_MT = language.Make("en_MT")
var tag_en_MU = language.Make("en_MU")
var tag_en_MW = language.Make("en_MW")
var tag_en_MY = language.Make("en_MY")
var tag_en_NA = language.Make("en_NA")
var tag_en_NF = language.Make("en_NF")
var tag_en_NG = language.Make("en_NG")
var tag_en_NL = language.Make("en_NL")
var tag_en_NR = language.Make("en_NR")
var tag_en_NU = language.Make("en_NU")
var tag_en_NZ = language.Make("en_NZ")
var tag_en_PG = language.Make("en_PG")
var tag_en_PH = language.Make("en_PH")
var tag_en_PK = language.Make("en_PK")
var tag_en_PN = language.Make("en_PN")
var tag_en_PR = language.Make("en_PR")
var tag_en_PW = language.Make("en_PW")
var tag_en_RW = language.Make("en_RW")
var tag_en_SB = language.Make("en_SB")
var tag_en_SC = language.Make("en_SC")
var tag_en_SD = language.Make("en_SD")
var tag_en_SE = language.Make("en_SE")
var tag_en_SG = language.Make("en_SG")
var tag_en_SH = language.Make("en_SH")
var tag_en_SI = language.Make("en_SI")
var tag_en_SL = language.Make("en_SL")
var tag_en_SS = language.Make("en_SS")
var tag_en_SX = language.Make("en_SX")
var tag_en_SZ = language.Make("en_SZ")
var tag_en_TC = language.Make("en_TC")
var tag_en_TK = language.Make("en_TK")
var tag_en_TO = language.Make("en_TO")
var tag_en_TT = language.Make("en_TT")
var tag_en_TV = language.Make("en_TV")
var tag_en_TZ = language.Make("en_TZ")
var tag_en_UG = language.Make("en_UG")
var tag_en_UM = language.Make("en_UM")
var tag_en_US = language.Make("en_US")
var tag_en_US_POSIX = language.Make("en_US_POSIX")
var tag_en_VC = language.Make("en_VC")
var tag_en_VG = language.Make("en_VG")
var tag_en_VI = language.Make("en_VI")
var tag_en_VU = language.Make("en_VU")
var tag_en_WS = language.Make("en_WS")
var tag_en_ZA = language.Make("en_ZA")
var tag_en_ZM = language.Make("en_ZM")
var tag_en_ZW = language.Make("en_ZW")
var tag_eo = language.Make("eo")
var tag_eo_001 = language.Make("eo_001")
var tag_es = language.Make("es")
var tag_es_419 = language.Make("es_419")
var tag_es_AR = language.Make("es_AR")
var tag_es_BO = language.Make("es_BO")
var tag_es_BR = language.Make("es_BR")
var tag_es_BZ = language.Make("es_BZ")
var tag_es_CL = language.Make("es_CL")
var tag_es_CO = language.Make("es_CO")
var tag_es_CR = language.Make("es_CR")
var tag_es_CU = language.Make("es_CU")
var tag_es_DO = language.Make("es_DO")
var tag_es_EA = language.Make("es_EA")
var tag_es_EC = language.Make("es_EC")
var tag_es_ES = language.Make("es_ES")
var tag_es_GQ = language.Make("es_GQ")
var tag_es_GT = language.Make("es_GT")
var tag_es_HN = language.Make("es_HN")
var tag_es_IC = language.Make("es_IC")
var tag_es_MX = language.Make("es_MX")
var tag_es_NI = language.Make("es_NI")
var tag_es_PA = language.Make("es_PA")
var tag_es_PE = language.Make("es_PE")
var tag_es_PH = language.Make("es_PH")
var tag_es_PR = language.Make("es_PR")
var tag_es_PY = language.Make("es_PY")
var tag_es_SV = language.Make("es_SV")
var tag_es_US = language.Make("es_US")
var tag_es_UY = language.Make("es_UY")
var tag_es_VE = language.Make("es_VE")
var tag_et = language.Make("et")
var tag_et_EE = language.Make("et_EE")
var tag_eu = language.Make("eu")
var tag_eu_ES = language.Make("eu_ES")
var tag_ewo = language.Make("ewo")
var tag_ewo_CM = language.Make("ewo_CM")
var tag_fa = language.Make("fa")
var tag_fa_AF = language.Make("fa_AF")
var tag_fa_IR = language.Make("fa_IR")
var tag_ff = language.Make("ff")
var tag_ff_Adlm = language.Make("ff_Adlm")
var tag_ff_Adlm_BF = language.Make("ff_Adlm_BF")
var tag_ff_Adlm_CM = language.Make("ff_Adlm_CM")
var tag_ff_Adlm_GH = language.Make("ff_Adlm_GH")
var tag_ff_Adlm_GM = language.Make("ff_Adlm_GM")
var tag_ff_Adlm_GN = language.Make("ff_Adlm_GN")
var tag_ff_Adlm_GW = language.Make("ff_Adlm_GW")
var tag_ff_Adlm_LR = language.Make("ff_Adlm_LR")
var tag_ff_Adlm_MR = language.Make("ff_Adlm_MR")
var tag_ff_Adlm_NE = language.Make("ff_Adlm_NE")
var tag_ff_Adlm_NG = language.Make("ff_Adlm_NG")
var tag_ff_Adlm_SL = language.Make("ff_Adlm_SL")
var tag_ff_Adlm_SN = language.Make("ff_Adlm_SN")
var tag_ff_Latn = language.Make("ff_Latn")
var tag_ff_Latn_BF = language.Make("ff_Latn_BF")
var tag_ff_Latn_CM = language.Make("ff_Latn_CM")
var tag_ff_Latn_GH = language.Make("ff_Latn_GH")
var tag_ff_Latn_GM = language.Make("ff_Latn_GM")
var tag_ff_Latn_GN = language.Make("ff_Latn_GN")
var tag_ff_Latn_GW = language.Make("ff_Latn_GW")
var tag_ff_Latn_LR = language.Make("ff_Latn_LR")
var tag_ff_Latn_MR = language.Make("ff_Latn_MR")
var tag_ff_Latn_NE = language.Make("ff_Latn_NE")
var tag_ff_Latn_NG = language.Make("ff_Latn_NG")
var tag_ff_Latn_SL = language.Make("ff_Latn_SL")
var tag_ff_Latn_SN = language.Make("ff_Latn_SN")
var tag_fi = language.Make("fi")
var tag_fi_FI = language.Make("fi_FI")
var tag_fil = language.Make("fil")
var tag_fil_PH = language.Make("fil_PH")
var tag_fo = language.Make("fo")
var tag_fo_DK = language.Make("fo_DK")
var tag_fo_FO = language.Make("fo_FO")
var tag_fr = language.Make("fr")
var tag_fr_BE = language.Make("fr_BE")
var tag_fr_BF = language.Make("fr_BF")
var tag_fr_BI = language.Make("fr_BI")
var tag_fr_BJ = language.Make("fr_BJ")
var tag_fr_BL = language.Make("fr_BL")
var tag_fr_CA = language.Make("fr_CA")
var tag_fr_CD = language.Make("fr_CD")
var tag_fr_CF = language.Make("fr_CF")
var tag_fr_CG = language.Make("fr_CG")
var tag_fr_CH = language.Make("fr_CH")
var tag_fr_CI = language.Make("fr_CI")
var tag_fr_CM = language.Make("fr_CM")
var tag_fr_DJ = language.Make("fr_DJ")
var tag_fr_DZ = language.Make("fr_DZ")
var tag_fr_FR = language.Make("fr_FR")
var tag_fr_GA = language.Make("fr_GA")
var tag_fr_GF = language.Make("fr_GF")
var tag_fr_GN = language.Make("fr_GN")
var tag_fr_GP = language.Make("fr_GP")
var tag_fr_GQ = language.Make("fr_GQ")
var tag_fr_HT = language.Make("fr_HT")
var tag_fr_KM = language.Make("fr_KM")
var tag_fr_LU = language.Make("fr_LU")
var tag_fr_MA = language.Make("fr_MA")
var tag_fr_MC = language.Make("fr_MC")
var tag_fr_MF = language.Make("fr_MF")
var tag_fr_MG = language.Make("fr_MG")
var tag_fr_ML = language.Make("fr_ML")
var tag_fr_MQ = language.Make("fr_MQ")
var tag_fr_MR = language.Make("fr_MR")
var tag_fr_MU = language.Make("fr_MU")
var tag_fr_NC = language.Make("fr_NC")
var tag_fr_NE = language.Make("fr_NE")
var tag_fr_PF = language.Make("fr_PF")
var tag_fr_PM = language.Make("fr_PM")
var tag_fr_RE = language.Make("fr_RE")
var tag_fr_RW = language.Make("fr_RW")
var tag_fr_SC = language.Make("fr_SC")
var tag_fr_SN = language.Make("fr_SN")
var tag_fr_SY = language.Make("fr_SY")
var tag_fr_TD = language.Make("fr_TD")
var tag_fr_TG = language.Make("fr_TG")
var tag_fr_TN = language.Make("fr_TN")
var tag_fr_VU = language.Make("fr_VU")
var tag_fr_WF = language.Make("fr_WF")
var tag_fr_YT = language.Make("fr_YT")
var tag_fur = language.Make("fur")
var tag_fur_IT = language.Make("fur_IT")
var tag_fy = language.Make("fy")
var tag_fy_NL = language.Make("fy_NL")
var tag_ga = language.Make("ga")
var tag_ga_GB = language.Make("ga_GB")
var tag_ga_IE = language.Make("ga_IE")
var tag_gd = language.Make("gd")
var tag_gd_GB = language.Make("gd_GB")
var tag_gl = language.Make("gl")
var tag_gl_ES = language.Make("gl_ES")
var tag_gsw = language.Make("gsw")
var tag_gsw_CH = language.Make("gsw_CH")
var tag_gsw_FR = language.Make("gsw_FR")
var tag_gsw_LI = language.Make("gsw_LI")
var tag_gu = language.Make("gu")
var tag_gu_IN = language.Make("gu_IN")
var tag_guw = language.Make("guw")
var tag_guz = language.Make("guz")
var tag_guz_KE = language.Make("guz_KE")
var tag_gv = language.Make("gv")
var tag_gv_IM = language.Make("gv_IM")
var tag_ha = language.Make("ha")
var tag_ha_GH = language.Make("ha_GH")
var tag_ha_NE = language.Make("ha_NE")
var tag_ha_NG = language.Make("ha_NG")
var tag_haw = language.Make("haw")
var tag_haw_US = language.Make("haw_US")
var tag_he = language.Make("he")
var tag_he_IL = language.Make("he_IL")
var tag_hi = language.Make("hi")
var tag_hi_IN = language.Make("hi_IN")
var tag_hr = language.Make("hr")
var tag_hr_BA = language.Make("hr_BA")
var tag_hr_HR = language.Make("hr_HR")
var tag_hsb = language.Make("hsb")
var tag_hsb_DE = language.Make("hsb_DE")
var tag_hu = language.Make("hu")
var tag_hu_HU = language.Make("hu_HU")
var tag_hy = language.Make("hy")
var tag_hy_AM = language.Make("hy_AM")
var tag_ia = language.Make("ia")
var tag_ia_001 = language.Make("ia_001")
var tag_id = language.Make("id")
var tag_id_ID = language.Make("id_ID")
var tag_ig = language.Make("ig")
var tag_ig_NG = language.Make("ig_NG")
var tag_ii = language.Make("ii")
var tag_ii_CN = language.Make("ii_CN")
var tag_in = language.Make("in")
var tag_io = language.Make("io")
var tag_is = language.Make("is")
var tag_is_IS = language.Make("is_IS")
var tag_it = language.Make("it")
var tag_it_CH = language.Make("it_CH")
var tag_it_IT = language.Make("it_IT")
var tag_it_SM = language.Make("it_SM")
var tag_it_VA = language.Make("it_VA")
var tag_iu = language.Make("iu")
var tag_iw = language.Make("iw")
var tag_ja = language.Make("ja")
var tag_ja_JP = language.Make("ja_JP")
var tag_jbo = language.Make("jbo")
var tag_jgo = language.Make("jgo")
var tag_jgo_CM = language.Make("jgo_CM")
var tag_ji = language.Make("ji")
var tag_jmc = language.Make("jmc")
var tag_jmc_TZ = language.Make("jmc_TZ")
var tag_jv = language.Make("jv")
var tag_jv_ID = language.Make("jv_ID")
var tag_jw = language.Make("jw")
var tag_ka = language.Make("ka")
var tag_ka_GE = language.Make("ka_GE")
var tag_kab = language.Make("kab")
var tag_kab_DZ = language.Make("kab_DZ")
var tag_kaj = language.Make("kaj")
var tag_kam = language.Make("kam")
var tag_kam_KE = language.Make("kam_KE")
var tag_kcg = language.Make("kcg")
var tag_kde = language.Make("kde")
var tag_kde_TZ = language.Make("kde_TZ")
var tag_kea = language.Make("kea")
var tag_kea_CV = language.Make("kea_CV")
var tag_khq = language.Make("khq")
var tag_khq_ML = language.Make("khq_ML")
var tag_ki = language.Make("ki")
var tag_ki_KE = language.Make("ki_KE")
var tag_kk = language.Make("kk")
var tag_kk_KZ = language.Make("kk_KZ")
var tag_kkj = language.Make("kkj")
var tag_kkj_CM = language.Make("kkj_CM")
var tag_kl = language.Make("kl")
var tag_kl_GL = language.Make("kl_GL")
var tag_kln = language.Make("kln")
var tag_kln_KE = language.Make("kln_KE")
var tag_km = language.Make("km")
var tag_km_KH = language.Make("km_KH")
var tag_kn = language.Make("kn")
var tag_kn_IN = language.Make("kn_IN")
var tag_ko = language.Make("ko")
var tag_ko_KP = language.Make("ko_KP")
var tag_ko_KR = language.Make("ko_KR")
var tag_kok = language.Make("kok")
var tag_kok_IN = language.Make("kok_IN")
var tag_ks = language.Make("ks")
var tag_ks_Arab = language.Make("ks_Arab")
var tag_ks_Arab_IN = language.Make("ks_Arab_IN")
var tag_ksb = language.Make("ksb")
var tag_ksb_TZ = language.Make("ksb_TZ")
var tag_ksf = language.Make("ksf")
var tag_ksf_CM = language.Make("ksf_CM")
var tag_ksh = language.Make("ksh")
var tag_ksh_DE = language.Make("ksh_DE")
var tag_ku = language.Make("ku")
var tag_ku_TR = language.Make("ku_TR")
var tag_kw = language.Make("kw")
var tag_kw_GB = language.Make("kw_GB")
var tag_ky = language.Make("ky")
var tag_ky_KG = language.Make("ky_KG")
var tag_lag = language.Make("lag")
var tag_lag_TZ = language.Make("lag_TZ")
var tag_lb = language.Make("lb")
var tag_lb_LU = language.Make("lb_LU")
var tag_lg = language.Make("lg")
var tag_lg_UG = language.Make("lg_UG")
var tag_lkt = language.Make("lkt")
var tag_lkt_US = language.Make("lkt_US")
var tag_ln = language.Make("ln")
var tag_ln_AO = language.Make("ln_AO")
var tag_ln_CD = language.Make("ln_CD")
var tag_ln_CF = language.Make("ln_CF")
var tag_ln_CG = language.Make("ln_CG")
var tag_lo = language.Make("lo")
var tag_lo_LA = language.Make("lo_LA")
var tag_lrc = language.Make("lrc")
var tag_lrc_IQ = language.Make("lrc_IQ")
var tag_lrc_IR = language.Make("lrc_IR")
var tag_lt = language.Make("lt")
var tag_lt_LT = language.Make("lt_LT")
var tag_lu = language.Make("lu")
var tag_lu_CD = language.Make("lu_CD")
var tag_luo = language.Make("luo")
var tag_luo_KE = language.Make("luo_KE")
var tag_luy = language.Make("luy")
var tag_luy_KE = language.Make("luy_KE")
var tag_lv = language.Make("lv")
var tag_lv_LV = language.Make("lv_LV")
var tag_mai = language.Make("mai")
var tag_mai_IN = language.Make("mai_IN")
var tag_mas = language.Make("mas")
var tag_mas_KE = language.Make("mas_KE")
var tag_mas_TZ = language.Make("mas_TZ")
var tag_mer = language.Make("mer")
var tag_mer_KE = language.Make("mer_KE")
var tag_mfe = language.Make("mfe")
var tag_mfe_MU = language.Make("mfe_MU")
var tag_mg = language.Make("mg")
var tag_mg_MG = language.Make("mg_MG")
var tag_mgh = language.Make("mgh")
var tag_mgh_MZ = language.Make("mgh_MZ")
var tag_mgo = language.Make("mgo")
var tag_mgo_CM = language.Make("mgo_CM")
var tag_mi = language.Make("mi")
var tag_mi_NZ = language.Make("mi_NZ")
var tag_mk = language.Make("mk")
var tag_mk_MK = language.Make("mk_MK")
var tag_ml = language.Make("ml")
var tag_ml_IN = language.Make("ml_IN")
var tag_mn = language.Make("mn")
var tag_mn_MN = language.Make("mn_MN")
var tag_mni = language.Make("mni")
var tag_mni_Beng = language.Make("mni_Beng")
var tag_mni_Beng_IN = language.Make("mni_Beng_IN")
var tag_mo = language.Make("mo")
var tag_mr = language.Make("mr")
var tag_mr_IN = language.Make("mr_IN")
var tag_ms = language.Make("ms")
var tag_ms_BN = language.Make("ms_BN")
var tag_ms_ID = language.Make("ms_ID")
var tag_ms_MY = language.Make("ms_MY")
var tag_ms_SG = language.Make("ms_SG")
var tag_mt = language.Make("mt")
var tag_mt_MT = language.Make("mt_MT")
var tag_mua = language.Make("mua")
var tag_mua_CM = language.Make("mua_CM")
var tag_my = language.Make("my")
var tag_my_MM = language.Make("my_MM")
var tag_mzn = language.Make("mzn")
var tag_mzn_IR = language.Make("mzn_IR")
var tag_nah = language.Make("nah")
var tag_naq = language.Make("naq")
var tag_naq_NA = language.Make("naq_NA")
var tag_nb = language.Make("nb")
var tag_nb_NO = language.Make("nb_NO")
var tag_nb_SJ = language.Make("nb_SJ")
var tag_nd = language.Make("nd")
var tag_nd_ZW = language.Make("nd_ZW")
var tag_nds = language.Make("nds")
var tag_nds_DE = language.Make("nds_DE")
var tag_nds_NL = language.Make("nds_NL")
var tag_ne = language.Make("ne")
var tag_ne_IN = language.Make("ne_IN")
var tag_ne_NP = language.Make("ne_NP")
var tag_nl = language.Make("nl")
var tag_nl_AW = language.Make("nl_AW")
var tag_nl_BE = language.Make("nl_BE")
var tag_nl_BQ = language.Make("nl_BQ")
var tag_nl_CW = language.Make("nl_CW")
var tag_nl_NL = language.Make("nl_NL")
var tag_nl_SR = language.Make("nl_SR")
var tag_nl_SX = language.Make("nl_SX")
var tag_nmg = language.Make("nmg")
var tag_nmg_CM = language.Make("nmg_CM")
var tag_nn = language.Make("nn")
var tag_nn_NO = language.Make("nn_NO")
var tag_nnh = language.Make("nnh")
var tag_nnh_CM = language.Make("nnh_CM")
var tag_no = language.Make("no")
var tag_nqo = language.Make("nqo")
var tag_nr = language.Make("nr")
var tag_nso = language.Make("nso")
var tag_nus = language.Make("nus")
var tag_nus_SS = language.Make("nus_SS")
var tag_ny = language.Make("ny")
var tag_nyn = language.Make("nyn")
var tag_nyn_UG = language.Make("nyn_UG")
var tag_om = language.Make("om")
var tag_om_ET = language.Make("om_ET")
var tag_om_KE = language.Make("om_KE")
var tag_or = language.Make("or")
var tag_or_IN = language.Make("or_IN")
var tag_os = language.Make("os")
var tag_os_GE = language.Make("os_GE")
var tag_os_RU = language.Make("os_RU")
var tag_osa = language.Make("osa")
var tag_pa = language.Make("pa")
var tag_pa_Arab = language.Make("pa_Arab")
var tag_pa_Arab_PK = language.Make("pa_Arab_PK")
var tag_pa_Guru = language.Make("pa_Guru")
var tag_pa_Guru_IN = language.Make("pa_Guru_IN")
var tag_pap = language.Make("pap")
var tag_pcm = language.Make("pcm")
var tag_pcm_NG = language.Make("pcm_NG")
var tag_pl = language.Make("pl")
var tag_pl_PL = language.Make("pl_PL")
var tag_prg = language.Make("prg")
var tag_prg_001 = language.Make("prg_001")
var tag_ps = language.Make("ps")
var tag_ps_AF = language.Make("ps_AF")
var tag_ps_PK = language.Make("ps_PK")
var tag_pt = language.Make("pt")
var tag_pt_AO = language.Make("pt_AO")
var tag_pt_BR = language.Make("pt_BR")
var tag_pt_CH = language.Make("pt_CH")
var tag_pt_CV = language.Make("pt_CV")
var tag_pt_GQ = language.Make("pt_GQ")
var tag_pt_GW = language.Make("pt_GW")
var tag_pt_LU = language.Make("pt_LU")
var tag_pt_MO = language.Make("pt_MO")
var tag_pt_MZ = language.Make("pt_MZ")
var tag_pt_PT = language.Make("pt_PT")
var tag_pt_ST = language.Make("pt_ST")
var tag_pt_TL = language.Make("pt_TL")
var tag_qu = language.Make("qu")
var tag_qu_BO = language.Make("qu_BO")
var tag_qu_EC = language.Make("qu_EC")
var tag_qu_PE = language.Make("qu_PE")
var tag_rm = language.Make("rm")
var tag_rm_CH = language.Make("rm_CH")
var tag_rn = language.Make("rn")
var tag_rn_BI = language.Make("rn_BI")
var tag_ro = language.Make("ro")
var tag_ro_MD = language.Make("ro_MD")
var tag_ro_RO = language.Make("ro_RO")
var tag_rof = language.Make("rof")
var tag_rof_TZ = language.Make("rof_TZ")
var tag_root = language.Make("root")
var tag_ru = language.Make("ru")
var tag_ru_BY = language.Make("ru_BY")
var tag_ru_KG = language.Make("ru_KG")
var tag_ru_KZ = language.Make("ru_KZ")
var tag_ru_MD = language.Make("ru_MD")
var tag_ru_RU = language.Make("ru_RU")
var tag_ru_UA = language.Make("ru_UA")
var tag_rw = language.Make("rw")
var tag_rw_RW = language.Make("rw_RW")
var tag_rwk = language.Make("rwk")
var tag_rwk_TZ = language.Make("rwk_TZ")
var tag_sah = language.Make("sah")
var tag_sah_RU = language.Make("sah_RU")
var tag_saq = language.Make("saq")
var tag_saq_KE = language.Make("saq_KE")
var tag_sat = language.Make("sat")
var tag_sat_Olck = language.Make("sat_Olck")
var tag_sat_Olck_IN = language.Make("sat_Olck_IN")
var tag_sbp = language.Make("sbp")
var tag_sbp_TZ = language.Make("sbp_TZ")
var tag_sc = language.Make("sc")
var tag_scn = language.Make("scn")
var tag_sd = language.Make("sd")
var tag_sd_Arab = language.Make("sd_Arab")
var tag_sd_Arab_PK = language.Make("sd_Arab_PK")
var tag_sd_Deva = language.Make("sd_Deva")
var tag_sd_Deva_IN = language.Make("sd_Deva_IN")
var tag_sdh = language.Make("sdh")
var tag_se = language.Make("se")
var tag_se_FI = language.Make("se_FI")
var tag_se_NO = language.Make("se_NO")
var tag_se_SE = language.Make("se_SE")
var tag_seh = language.Make("seh")
var tag_seh_MZ = language.Make("seh_MZ")
var tag_ses = language.Make("ses")
var tag_ses_ML = language.Make("ses_ML")
var tag_sg = language.Make("sg")
var tag_sg_CF = language.Make("sg_CF")
var tag_sh = language.Make("sh")
var tag_shi = language.Make("shi")
var tag_shi_Latn = language.Make("shi_Latn")
var tag_shi_Latn_MA = language.Make("shi_Latn_MA")
var tag_shi_Tfng = language.Make("shi_Tfng")
var tag_shi_Tfng_MA = language.Make("shi_Tfng_MA")
var tag_si = language.Make("si")
var tag_si_LK = language.Make("si_LK")
var tag_sk = language.Make("sk")
var tag_sk_SK = language.Make("sk_SK")
var tag_sl = language.Make("sl")
var tag_sl_SI = language.Make("sl_SI")
var tag_sma = language.Make("sma")
var tag_smi = language.Make("smi")
var tag_smj = language.Make("smj")
var tag_smn = language.Make("smn")
var tag_smn_FI = language.Make("smn_FI")
var tag_sms = language.Make("sms")
var tag_sn = language.Make("sn")
var tag_sn_ZW = language.Make("sn_ZW")
var tag_so = language.Make("so")
var tag_so_DJ = language.Make("so_DJ")
var tag_so_ET = language.Make("so_ET")
var tag_so_KE = language.Make("so_KE")
var tag_so_SO = language.Make("so_SO")
var tag_sq = language.Make("sq")
var tag_sq_AL = language.Make("sq_AL")
var tag_sq_MK = language.Make("sq_MK")
var tag_sq_XK = language.Make("sq_XK")
var tag_sr = language.Make("sr")
var tag_sr_Cyrl = language.Make("sr_Cyrl")
var tag_sr_Cyrl_BA = language.Make("sr_Cyrl_BA")
var tag_sr_Cyrl_ME = language.Make("sr_Cyrl_ME")
var tag_sr_Cyrl_RS = language.Make("sr_Cyrl_RS")
var tag_sr_Cyrl_XK = language.Make("sr_Cyrl_XK")
var tag_sr_Latn = language.Make("sr_Latn")
var tag_sr_Latn_BA = language.Make("sr_Latn_BA")
var tag_sr_Latn_ME = language.Make("sr_Latn_ME")
var tag_sr_Latn_RS = language.Make("sr_Latn_RS")
var tag_sr_Latn_XK = language.Make("sr_Latn_XK")
var tag_ss = language.Make("ss")
var tag_ssy = language.Make("ssy")
var tag_st = language.Make("st")
var tag_su = language.Make("su")
var tag_su_Latn = language.Make("su_Latn")
var tag_su_Latn_ID = language.Make("su_Latn_ID")
var tag_sv = language.Make("sv")
var tag_sv_AX = language.Make("sv_AX")
var tag_sv_FI = language.Make("sv_FI")
var tag_sv_SE = language.Make("sv_SE")
var tag_sw = language.Make("sw")
var tag_sw_CD = language.Make("sw_CD")
var tag_sw_KE = language.Make("sw_KE")
var tag_sw_TZ = language.Make("sw_TZ")
var tag_sw_UG = language.Make("sw_UG")
var tag_syr = language.Make("syr")
var tag_ta = language.Make("ta")
var tag_ta_IN = language.Make("ta_IN")
var tag_ta_LK = language.Make("ta_LK")
var tag_ta_MY = language.Make("ta_MY")
var tag_ta_SG = language.Make("ta_SG")
var tag_te = language.Make("te")
var tag_te_IN = language.Make("te_IN")
var tag_teo = language.Make("teo")
var tag_teo_KE = language.Make("teo_KE")
var tag_teo_UG = language.Make("teo_UG")
var tag_tg = language.Make("tg")
var tag_tg_TJ = language.Make("tg_TJ")
var tag_th = language.Make("th")
var tag_th_TH = language.Make("th_TH")
var tag_ti = language.Make("ti")
var tag_ti_ER = language.Make("ti_ER")
var tag_ti_ET = language.Make("ti_ET")
var tag_tig = language.Make("tig")
var tag_tk = language.Make("tk")
var tag_tk_TM = language.Make("tk_TM")
var tag_tl = language.Make("tl")
var tag_tn = language.Make("tn")
var tag_to = language.Make("to")
var tag_to_TO = language.Make("to_TO")
var tag_tr = language.Make("tr")
var tag_tr_CY = language.Make("tr_CY")
var tag_tr_TR = language.Make("tr_TR")
var tag_ts = language.Make("ts")
var tag_tt = language.Make("tt")
var tag_tt_RU = language.Make("tt_RU")
var tag_twq = language.Make("twq")
var tag_twq_NE = language.Make("twq_NE")
var tag_tzm = language.Make("tzm")
var tag_tzm_MA = language.Make("tzm_MA")
var tag_ug = language.Make("ug")
var tag_ug_CN = language.Make("ug_CN")
var tag_uk = language.Make("uk")
var tag_uk_UA = language.Make("uk_UA")
var tag_ur = language.Make("ur")
var tag_ur_IN = language.Make("ur_IN")
var tag_ur_PK = language.Make("ur_PK")
var tag_uz = language.Make("uz")
var tag_uz_Arab = language.Make("uz_Arab")
var tag_uz_Arab_AF = language.Make("uz_Arab_AF")
var tag_uz_Cyrl = language.Make("uz_Cyrl")
var tag_uz_Cyrl_UZ = language.Make("uz_Cyrl_UZ")
var tag_uz_Latn = language.Make("uz_Latn")
var tag_uz_Latn_UZ = language.Make("uz_Latn_UZ")
var tag_vai = language.Make("vai")
var tag_vai_Latn = language.Make("vai_Latn")
var tag_vai_Latn_LR = language.Make("vai_Latn_LR")
var tag_vai_Vaii = language.Make("vai_Vaii")
var tag_vai_Vaii_LR = language.Make("vai_Vaii_LR")
var tag_ve = language.Make("ve")
var tag_vi = language.Make("vi")
var tag_vi_VN = language.Make("vi_VN")
var tag_vo = language.Make("vo")
var tag_vo_001 = language.Make("vo_001")
var tag_vun = language.Make("vun")
var tag_vun_TZ = language.Make("vun_TZ")
var tag_wa = language.Make("wa")
var tag_wae = language.Make("wae")
var tag_wae_CH = language.Make("wae_CH")
var tag_wo = language.Make("wo")
var tag_wo_SN = language.Make("wo_SN")
var tag_xh = language.Make("xh")
var tag_xh_ZA = language.Make("xh_ZA")
var tag_xog = language.Make("xog")
var tag_xog_UG = language.Make("xog_UG")
var tag_yav = language.Make("yav")
var tag_yav_CM = language.Make("yav_CM")
var tag_yi = language.Make("yi")
var tag_yi_001 = language.Make("yi_001")
var tag_yo = language.Make("yo")
var tag_yo_BJ = language.Make("yo_BJ")
var tag_yo_NG = language.Make("yo_NG")
var tag_yue = language.Make("yue")
var tag_yue_Hans = language.Make("yue_Hans")
var tag_yue_Hans_CN = language.Make("yue_Hans_CN")
var tag_yue_Hant = language.Make("yue_Hant")
var tag_yue_Hant_HK = language.Make("yue_Hant_HK")
var tag_zgh = language.Make("zgh")
var tag_zgh_MA = language.Make("zgh_MA")
var tag_zh = language.Make("zh")
var tag_zh_Hans = language.Make("zh_Hans")
var tag_zh_Hans_CN = language.Make("zh_Hans_CN")
var tag_zh_Hans_HK = language.Make("zh_Hans_HK")
var tag_zh_Hans_MO = language.Make("zh_Hans_MO")
var tag_zh_Hans_SG = language.Make("zh_Hans_SG")
var tag_zh_Hant = language.Make("zh_Hant")
var tag_zh_Hant_HK = language.Make("zh_Hant_HK")
var tag_zh_Hant_MO = language.Make("zh_Hant_MO")
var tag_zh_Hant_TW = language.Make("zh_Hant_TW")
var tag_zu = language.Make("zu")
var tag_zu_ZA = language.Make("zu_ZA")
